import type { LevelMapConfig } from "../../schema/levelConfig";
import {
  createOfficialExitElevatorReferenceProps,
  createOfficialExitRoomReference,
  officialExitDoorAnimationReference,
} from "../../shared/exitRoomReference";

export const level02Map: LevelMapConfig = {
    id: "level_02_residential_simulation_map",
    schemaVersion: "hp.map.v1",
    presentation: {
      archetype: "large_combat_arena",
      shellKit: "hp:residential_false_home_shell_v1",
      lightingPreset: "hp:residential_simulation_false_home_story_v1",
      doorKit: "hp:residential_hidden_door_quiet_v1",
      propSet: "hp:residential_simulation_props_v1",
      spawnLayout: "hp:perimeter_wave_spawns_v1",
      pickupLayout: "hp:readable_center_pickups_v1",
      previewCamera: "hp:residential_living_showcase_v1",
      overrides: {
        propDensity: "medium",
        floorWear: 0.39,
        ceilingLightIntensity: 0.92,
        doorStateStyle: "story_red_to_cyan",
        pickupVisibility: "critical_items_high",
        fogFar: 93.56,
      },
    },
    rooms: [
      {
        id: "level_02_recovery_foyer",
        label: "恢复前厅",
        bounds: { center: [0, 0, 12.1], size: [12.5, 4, 7.4] },
        mood: "quiet",
        floorMaterialKey: "residential_floor",
        wallMaterialKey: "residential_wall",
        entryDialogueTrigger: "level_start",
        ambientPressure: 0.22,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#d6b678" },
        aesthetic: { style: "residential", detail: "medium" },
      },
      {
        id: "level_02_living_room",
        label: "生活模拟大厅",
        bounds: { center: [0, 0, 0.4], size: [18.8, 4, 16.6] },
        mood: "combat",
        floorMaterialKey: "residential_floor",
        wallMaterialKey: "residential_wall",
        entryDialogueTrigger: "level_02_living_entry",
        ambientPressure: 0.56,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#d6b678" },
        aesthetic: { style: "residential", detail: "high" },
      },
      {
        id: "level_02_care_room",
        label: "家政维修间",
        bounds: { center: [13, 0, 0.4], size: [7.2, 4, 7.8] },
        mood: "boss",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        entryDialogueTrigger: "level_02_care_room_entered",
        ambientPressure: 0.82,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ffb34f" },
        aesthetic: { style: "hazard", detail: "high" },
      },
      {
        id: "level_02_light_room",
        label: "家庭灯控室",
        bounds: { center: [-13, 0, 0.4], size: [7.2, 4, 7.8] },
        mood: "uneasy",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        ambientPressure: 0.7,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#7ff2ff" },
        aesthetic: { style: "sterile", detail: "high" },
      },
      createOfficialExitRoomReference({
        id: "level_02_exit_elevator_room",
        label: "尽头电梯",
        doorPosition: [0, 0, -7.9],
      }),
    ],
    doors: [
      {
        id: "level_02_living_room_door",
        label: "生活区门",
        fromRoomId: "level_02_recovery_foyer",
        toRoomId: "level_02_living_room",
        position: [0, 0, 8.55],
        size: [2.7, 2.72, 0.34],
        yaw: 0,
        defaultState: "closed",
        lock: { type: "none", unlockedMessage: "生活区门已打开。" },
        visualKey: "residential_access_door",
        materialKey: "residential_wall",
        openSpeed: 1.18,
        openVisualPolicy: { hideClosedHardwareAfterOpen: true, hidePanelAfterOpen: true },
        cameraImpact: { shake: 0.12, fovKick: 0.65 },
      },
      {
        id: "level_02_care_room_door",
        label: "家政维修间门",
        fromRoomId: "level_02_living_room",
        toRoomId: "level_02_care_room",
        position: [9.4, 0, 0.4],
        size: [2.05, 2.58, 0.32],
        yaw: Math.PI / 2,
        defaultState: "locked",
        lock: {
          type: "survive_wave",
          waveId: "level_02_living_swarm",
          lockedMessage: "先清掉生活模拟大厅里的家政单位。",
          unlockedMessage: "大厅威胁清除，家政维修间已解锁。",
        },
        visualKey: "residential_access_door",
        materialKey: "residential_wall",
        panelPosition: [8.95, 0, 1.85],
        openSpeed: 1.22,
        openVisualPolicy: { hideClosedHardwareAfterOpen: true, hidePanelAfterOpen: true },
        openedDialogueTrigger: "level_02_care_room_open",
        cameraImpact: { shake: 0.18, fovKick: 0.9 },
      },
      {
        id: "level_02_light_room_door",
        label: "家庭灯控室门",
        fromRoomId: "level_02_living_room",
        toRoomId: "level_02_light_room",
        position: [-9.4, 0, 0.4],
        size: [2.05, 2.58, 0.32],
        yaw: Math.PI / 2,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "level_02_care_room_puzzle",
          lockedMessage: "先完成家政维修间的工具档案校准。",
          unlockedMessage: "灯控室门已打开。",
        },
        visualKey: "residential_access_door",
        materialKey: "residential_wall",
        panelPosition: [-8.95, 0, 1.85],
        openSpeed: 1.22,
        openVisualPolicy: { hideClosedHardwareAfterOpen: true },
        closedDialogueTrigger: "level_02_light_room_locked",
        openedDialogueTrigger: "level_02_light_room_open",
        cameraImpact: { shake: 0.2, fovKick: 1.1 },
      },
      {
        id: "level_02_family_exit_door",
        label: "尽头电梯门",
        fromRoomId: "level_02_living_room",
        toRoomId: "level_02_exit_elevator_room",
        position: [0, 0, -7.9],
        size: [4.5, 3.4, 0.42],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "level_02_light_sequence",
          lockedMessage: "家庭门禁等待灯控顺序。",
          unlockedMessage: "家庭门禁已打开。",
        },
        ...officialExitDoorAnimationReference,
        panelPosition: [2.68, 0, -7.55],
        cameraImpact: { shake: 0.42, fovKick: 2.2, rumble: 0.22, rumbleDuration: 0.25 },
      },
    ],
    keyItems: [],
    interactions: [
      {
        id: "level_02_care_panel",
        type: "terminal",
        roomId: "level_02_care_room",
        position: [13, 0, 1.4],
        radius: 1.85,
        visualKey: "direction_keypad_panel",
        materialKey: "terminal_cyan",
        label: "家政维修台",
        requiresObjectiveId: "obj_survive_level_02_carekeeper_host",
      },
      {
        id: "level_02_observation_panel",
        type: "terminal",
        roomId: "level_02_light_room",
        position: [-13, 0, 1.4],
        radius: 1.8,
        visualKey: "direction_keypad_panel",
        materialKey: "terminal_cyan",
        label: "家庭观察台",
      },
      {
        id: "use_builder_exit",
        type: "exit",
        roomId: "level_02_exit_elevator_room",
        position: [0, 0, -11.05],
        radius: 2.6,
        visualKey: "service_elevator_panel",
        materialKey: "terminal_cyan",
        label: "进入出口电梯",
        opensDoorId: "level_02_family_exit_door",
      },
    ],
    pickups: [
      {
        id: "level_02_foyer_repair_01",
        type: "repairKit",
        roomId: "level_02_recovery_foyer",
        position: [-3.2, 0, 12.85],
        visualKey: "maintenance_crate",
        label: "急救包",
      },
      {
        id: "level_02_foyer_repair_02",
        type: "repairKit",
        roomId: "level_02_recovery_foyer",
        position: [0, 0, 11.45],
        visualKey: "maintenance_crate",
        label: "急救包",
      },
      {
        id: "level_02_foyer_repair_03",
        type: "repairKit",
        roomId: "level_02_recovery_foyer",
        position: [3.2, 0, 12.85],
        visualKey: "maintenance_crate",
        label: "急救包",
      },
    ],
    props: [
      ...createOfficialExitElevatorReferenceProps({
        idPrefix: "level_02_official_exit",
        roomId: "level_02_exit_elevator_room",
        doorPosition: [0, 0, -7.9],
        tags: ["official", "level02", "residential_simulation"],
      }),
    ],
    navigation: {
      criticalPathRoomIds: [
        "level_02_recovery_foyer",
        "level_02_living_room",
        "level_02_care_room",
        "level_02_light_room",
        "level_02_exit_elevator_room",
      ],
      optionalRoomIds: [],
      maxBacktrackSeconds: 42,
      mobileReadableDoorCount: 4,
    },
  };
