import type { LevelObjectiveDefinition, LevelRuntimeEventDefinition } from "../../schema/levelConfig";

export const level02Objectives: readonly LevelObjectiveDefinition[] = [
    {
      id: "obj_survive_level_02_care_room_door",
      type: "survive_wave",
      title: "清掉生活模拟大厅",
      detail: "击毁大厅里的家政单位，右侧家政维修间才会解锁。",
      requiredIds: ["level_02_living_swarm"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "wave_completed", id: "level_02_living_swarm" },
      nextObjectiveId: "obj_open_level_02_care_room_door",
      hudLabel: "清剿",
      guidance: { targetType: "wave", targetId: "level_02_living_swarm", label: "生活模拟大厅", detail: "右门解锁条件", urgency: "danger" },
    },
    {
      id: "obj_open_level_02_care_room_door",
      type: "open_door",
      title: "打开家政维修间",
      detail: "大厅威胁清除后，打开右侧维修间门。",
      requiredIds: ["level_02_care_room_door"],
      startsWhen: { type: "objective_completed", id: "obj_survive_level_02_care_room_door" },
      completesWhen: { type: "door_opened", id: "level_02_care_room_door" },
      nextObjectiveId: "obj_survive_level_02_carekeeper_host",
      hudLabel: "右门",
      guidance: { targetType: "door", targetId: "level_02_care_room_door", label: "家政维修间", detail: "大厅东侧", urgency: "normal" },
    },
    {
      id: "obj_survive_level_02_carekeeper_host",
      type: "survive_wave",
      title: "击倒家政主管",
      detail: "主管守在维修间里。击倒它，再使用维修台。",
      requiredIds: ["level_02_carekeeper_host"],
      startsWhen: { type: "objective_completed", id: "obj_open_level_02_care_room_door" },
      completesWhen: { type: "wave_completed", id: "level_02_carekeeper_host" },
      nextObjectiveId: "obj_puzzle_level_02_light_room_door",
      hudLabel: "主管",
      guidance: { targetType: "wave", targetId: "level_02_carekeeper_host", label: "家政主管", detail: "右侧维修间", urgency: "danger" },
    },
    {
      id: "obj_puzzle_level_02_light_room_door",
      type: "custom",
      title: "校准家政维修台",
      detail: "把维修台回路接到灯控室门禁，打开大厅另一侧。",
      requiredIds: ["level_02_care_room_puzzle"],
      startsWhen: { type: "objective_completed", id: "obj_survive_level_02_carekeeper_host" },
      completesWhen: { type: "puzzle_completed", id: "level_02_care_room_puzzle" },
      nextObjectiveId: "obj_open_level_02_light_room_door",
      hudLabel: "维修台",
      guidance: { targetType: "puzzle", targetId: "level_02_care_room_puzzle", label: "家政维修台", detail: "右侧维修间", urgency: "puzzle" },
    },
    {
      id: "obj_open_level_02_light_room_door",
      type: "open_door",
      title: "打开家庭灯控室",
      detail: "维修台校准后，打开大厅另一侧的灯控室。",
      requiredIds: ["level_02_light_room_door"],
      startsWhen: { type: "objective_completed", id: "obj_puzzle_level_02_light_room_door" },
      completesWhen: { type: "door_opened", id: "level_02_light_room_door" },
      nextObjectiveId: "obj_puzzle_level_02_family_exit_door",
      hudLabel: "灯控室",
      guidance: { targetType: "door", targetId: "level_02_light_room_door", label: "家庭灯控室", detail: "大厅西侧", urgency: "normal" },
    },
    {
      id: "obj_puzzle_level_02_family_exit_door",
      type: "custom",
      title: "比对家庭作息",
      detail: "观察台回放四段作息，第四段不属于这个家。",
      requiredIds: ["level_02_light_sequence"],
      startsWhen: { type: "objective_completed", id: "obj_open_level_02_light_room_door" },
      completesWhen: { type: "puzzle_completed", id: "level_02_light_sequence" },
      nextObjectiveId: "obj_open_level_02_family_exit_door",
      hudLabel: "作息比对",
      guidance: { targetType: "puzzle", targetId: "level_02_light_sequence", label: "家庭观察台", detail: "第四段只有雪花", urgency: "puzzle" },
    },
    {
      id: "obj_open_level_02_family_exit_door",
      type: "open_door",
      title: "打开尽头电梯门",
      detail: "灯控顺序确认后，打开客厅尽头的电梯门。",
      requiredIds: ["level_02_family_exit_door"],
      startsWhen: { type: "objective_completed", id: "obj_puzzle_level_02_family_exit_door" },
      completesWhen: { type: "door_opened", id: "level_02_family_exit_door" },
      nextObjectiveId: "obj_reach_exit",
      hudLabel: "出口门",
      guidance: { targetType: "door", targetId: "level_02_family_exit_door", label: "尽头电梯门", detail: "客厅北侧", urgency: "exit" },
    },
    {
      id: "obj_reach_exit",
      type: "reach_exit",
      title: "穿过家庭门禁",
      detail: "灯控顺序确认后门已开。穿过客厅尽头进入电梯。",
      requiredIds: ["use_builder_exit"],
      startsWhen: { type: "objective_completed", id: "obj_open_level_02_family_exit_door" },
      completesWhen: { type: "interaction_completed", id: "use_builder_exit" },
      hudLabel: "撤离",
    },
  ];

export const level02Events: readonly LevelRuntimeEventDefinition[] = [
    {
      id: "level_02_light_sequence_memory",
      trigger: { type: "puzzle_completed", id: "level_02_light_sequence" },
      actions: [
        {
          type: "add_memory",
          amount: 10,
          rewardPulse: { label: "家庭测试记录 +10", detail: "出口门禁数据进入记忆缓存", rarity: "rare" },
          rewardPulseDuration: 1.55,
        },
        { type: "set_environment_state", stateId: "level_02_family_mask_off" },
        { type: "tempo_surge", duration: 3.8 },
      ],
    },
  ];
