import type { DialogueDefinition } from "../../dialogueScripts";
import type { LevelArticleDefinition } from "../../schema/levelConfig";

export const level02Dialogues: readonly DialogueDefinition[] = [
  {
    id: "level_02_start_01",
    trigger: "level_start",
    speaker: "耳机里",
    line: "这里像家，但门禁在听你呼吸。",
    tone: "system",
    duration: 2.7,
  },
  {
    id: "level_02_living_entry_01",
    trigger: "level_02_living_entry",
    speaker: "远处人声",
    line: "欢迎回家。请按旧习惯就座。",
    tone: "threat",
    duration: 2.9,
  },
  {
    id: "level_02_first_kill_01",
    trigger: "first_enemy_killed",
    speaker: "你",
    line: "它们不想杀我，只想让我留下。",
    tone: "player",
    duration: 2.6,
  },
  {
    id: "level_02_light_locked_01",
    trigger: "level_02_light_room_locked",
    speaker: "门禁",
    line: "家庭灯控室锁定。需完成照护校准。",
    tone: "threat",
    duration: 2.3,
  },
  {
    id: "level_02_living_clear_01",
    trigger: "level_02_living_clear",
    speaker: "门禁",
    line: "客厅反应稳定。照护间已开放。",
    tone: "system",
    duration: 2.4,
  },
  {
    id: "level_02_care_room_open_01",
    trigger: "level_02_care_room_open",
    speaker: "近处广播",
    line: "照护间开放。家政主管开始复位。",
    tone: "threat",
    duration: 2.5,
  },
  {
    id: "level_02_care_room_01",
    trigger: "level_02_care_room_entered",
    speaker: "耳机里",
    line: "主管守着校准台。先让它停机。",
    tone: "system",
    duration: 2.8,
  },
  {
    id: "level_02_host_spawn_01",
    trigger: "level_02_host_spawn",
    speaker: "家政主管",
    line: "未授权离家。执行安抚回收。",
    tone: "threat",
    duration: 3,
  },
  {
    id: "level_02_host_half_01",
    trigger: "elite_hp_50",
    speaker: "家政主管",
    line: "离开不是康复，是失配。",
    tone: "reveal",
    duration: 2.8,
  },
  {
    id: "level_02_host_down_01",
    trigger: "level_02_host_down",
    speaker: "未知频道",
    line: "主管离线。校准台现在归你。",
    tone: "reveal",
    duration: 2.8,
  },
  {
    id: "level_02_care_panel_done_01",
    trigger: "level_02_care_panel_done",
    speaker: "门禁",
    line: "照护校准完成。灯控室放行。",
    tone: "system",
    duration: 2.5,
  },
  {
    id: "level_02_light_room_open_01",
    trigger: "level_02_light_room_open",
    speaker: "门禁",
    line: "按旧作息开灯。看清这间屋子。",
    tone: "threat",
    duration: 2.6,
  },
  {
    id: "level_02_light_sequence_done_01",
    trigger: "level_02_light_sequence_done",
    speaker: "公寓广播",
    line: "墙纸下面不是墙，是维修管线。",
    tone: "reveal",
    duration: 2.9,
  },
  {
    id: "level_02_exit_01",
    trigger: "exit_entered",
    speaker: "档案残片",
    line: "居住模拟：对象会寻找“家”。",
    tone: "reveal",
    duration: 3,
  },
];

export const level02Articles = [] as const;
