import type { LevelMapConfig } from "../../schema/levelConfig";
import {
  createOfficialExitElevatorReferenceProps,
  createOfficialExitRoomReference,
  officialExitDoorAnimationReference,
} from "../../shared/exitRoomReference";

export const level01Map: LevelMapConfig = {
    id: "level_01_maintenance_bay_map",
    schemaVersion: "hp.map.v1",
    presentation: {
      roomKit: "hp:maintenance_combat_bay_v3_art_pass",
      archetype: "large_combat_arena",
      lightingPreset: "hp:cyan_lockdown_arena_v5_age_director",
      shellKit: "hp:industrial_panel_arena_shell_v4_image2_floor",
      doorKit: "hp:elevator_exit_lockable_v1",
      propSet: "hp:repair_bay_props_v1",
      spawnLayout: "hp:perimeter_wave_spawns_v1",
      pickupLayout: "hp:readable_center_pickups_v1",
      previewCamera: "hp:maintenance_repair_bay_showcase_v1",
      overrides: {
        propDensity: "medium",
        floorWear: 0.46,
        ceilingLightIntensity: 1,
        doorStateStyle: "lockdown_red_to_cyan",
        pickupVisibility: "critical_items_high",
      },
    },
    rooms: [
      {
        id: "maintenance_bay_floor",
        label: "维修主舱",
        bounds: { center: [0, 0, -3.2], size: [18, 4, 25] },
        mood: "combat",
        skinKey: "maintenance_bay_hero",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        entryDialogueTrigger: "level_start",
        ambientPressure: 0.45,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#8df6ff" },
        aesthetic: { style: "maintenance", detail: "high" },
      },
      {
        id: "level_01_tool_alcove",
        label: "工具间",
        bounds: { center: [-11.25, 0, 1.5], size: [4.5, 4, 6] },
        mood: "quiet",
        skinKey: "maintenance_service",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        ambientPressure: 0.36,
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ffd36d" },
        aesthetic: { style: "maintenance", detail: "high" },
      },
      createOfficialExitRoomReference({
        id: "service_elevator_room",
        label: "维修电梯井",
        doorPosition: [0, 0, -15.2],
      }),
    ],
    doors: [
      {
        id: "service_elevator_door",
        label: "维修电梯门",
        fromRoomId: "maintenance_bay_floor",
        toRoomId: "service_elevator_room",
        position: [0, 0, -15.2],
        size: [3.4, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "survive_wave",
          waveId: "first_contact",
          waveIds: ["first_contact", "wave_01", "wave_02", "elite_wave"],
          lockedMessage: "清掉维修主舱里的机器人，门才会开。",
          unlockedMessage: "维修电梯已解锁。",
        },
        ...officialExitDoorAnimationReference,
        panelPosition: [1.85, 0, -14.7],
        closedDialogueTrigger: "exit_unlocked",
        openedDialogueTrigger: "exit_entered",
        cameraImpact: { shake: 0.18, fovKick: 1.2 },
      },
      {
        id: "level_01_alcove_door",
        label: "工具间门",
        fromRoomId: "maintenance_bay_floor",
        toRoomId: "level_01_tool_alcove",
        position: [-9, 0, 1.5],
        size: [2.6, 3, 0.32],
        yaw: Math.PI / 2,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "industrial_access_door",
        materialKey: "hazard_hall_wall",
      },
    ],
    keyItems: [],
    interactions: [
      {
        id: "use_builder_exit",
        type: "exit",
        roomId: "service_elevator_room",
        position: [0, 0, -16.3],
        radius: 2.1,
        visualKey: "service_elevator_panel",
        label: "进入维修电梯",
        opensDoorId: "service_elevator_door",
        dialogueTrigger: "exit_entered",
      },
    ],
    pickups: [
      {
        id: "level_01_visible_repair_kit",
        type: "repairKit",
        roomId: "maintenance_bay_floor",
        position: [3.8, 0, 5.5],
        visualKey: "maintenance_crate",
        label: "修复箱",
      },
      {
        id: "level_01_visible_core_cell",
        type: "coreCell",
        roomId: "maintenance_bay_floor",
        position: [4.65, 0, 5.15],
        visualKey: "maintenance_crate",
        label: "应急电池",
      },
    ],
    props: [
      ...createOfficialExitElevatorReferenceProps({
        idPrefix: "level_01_official_exit",
        roomId: "service_elevator_room",
        doorPosition: [0, 0, -15.2],
        tags: ["official", "level01"],
      }),
      {
        id: "level_01_robot_storage_window",
        roomId: "maintenance_bay_floor",
        modelKey: "backdrop_robot_storage_window_dark",
        position: [-8.75, 0, 0.5],
        rotation: [0, 1.5707963267948966, 0],
        scale: 1,
        label: "机器人收纳窗",
        tags: ["official", "level01", "backdrop", "wall_asset", "configurable"],
      },
      {
        id: "level_01_back_wall_panel_left",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-6.6, 0, 9.08],
        rotation: [0, 0, 0],
        scale: [1.22, 1.18, 1],
        label: "后墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_back_wall_panel_mid_left",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-3.25, 0, 9.08],
        rotation: [0, 0, 0],
        scale: [1.22, 1.18, 1],
        label: "后墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_back_wall_panel_mid_right",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [3.25, 0, 9.08],
        rotation: [0, 0, 0],
        scale: [1.22, 1.18, 1],
        label: "后墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_back_wall_panel_right",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [6.6, 0, 9.08],
        rotation: [0, 0, 0],
        scale: [1.22, 1.18, 1],
        label: "后墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_left_maintenance_half_panel",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-6.6, 0, 1.2],
        rotation: [0, 1.5707963267948966, 0],
        scale: 1,
        label: "维修半墙",
        tags: ["official", "level01", "cover", "wall_asset", "configurable"],
      },
      {
        id: "level_01_left_wall_panel_spawn",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-8.78, 0, 6.5],
        rotation: [0, 1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "左墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_left_wall_panel_mid",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-8.78, 0, -3.2],
        rotation: [0, 1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "左墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_left_wall_panel_exit",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [-8.78, 0, -10.0],
        rotation: [0, 1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "左墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_right_maintenance_half_panel",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [6.8, 0, -2.6],
        rotation: [0, -1.5707963267948966, 0],
        scale: 1,
        label: "维修半墙",
        tags: ["official", "level01", "cover", "wall_asset", "configurable"],
      },
      {
        id: "level_01_right_wall_panel_spawn",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [8.78, 0, 6.2],
        rotation: [0, -1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "右墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_right_wall_panel_mid",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [8.78, 0, -5.3],
        rotation: [0, -1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "右墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_right_wall_panel_exit",
        roomId: "maintenance_bay_floor",
        modelKey: "room_wall_panel_maintenance",
        position: [8.78, 0, -10.8],
        rotation: [0, -1.5707963267948966, 0],
        scale: [1.18, 1.16, 1],
        label: "右墙维修板",
        tags: ["official", "level01", "wall_asset", "configurable"],
      },
      {
        id: "level_01_elevator_back_wall_panel",
        roomId: "service_elevator_room",
        modelKey: "room_wall_panel_maintenance",
        position: [0, 0, -17.72],
        rotation: [0, 0, 0],
        scale: [1.35, 1.18, 1],
        label: "电梯后墙维修板",
        tags: ["official", "level01", "wall_asset", "endpoint", "configurable"],
      },
      {
        id: "level_01_elevator_left_wall_panel",
        roomId: "service_elevator_room",
        modelKey: "room_wall_panel_maintenance",
        position: [-2.45, 0, -16.35],
        rotation: [0, 1.5707963267948966, 0],
        scale: [1.05, 1.12, 1],
        label: "电梯侧墙维修板",
        tags: ["official", "level01", "wall_asset", "endpoint", "configurable"],
      },
      {
        id: "level_01_elevator_right_wall_panel",
        roomId: "service_elevator_room",
        modelKey: "room_wall_panel_maintenance",
        position: [2.45, 0, -16.35],
        rotation: [0, -1.5707963267948966, 0],
        scale: [1.05, 1.12, 1],
        label: "电梯侧墙维修板",
        tags: ["official", "level01", "wall_asset", "endpoint", "configurable"],
      },
      {
        id: "level_01_overhead_cyan_flicker",
        roomId: "maintenance_bay_floor",
        modelKey: "light_ceiling_flicker_cyan_2m",
        position: [-2.2, 2.9, 3.4],
        rotation: [0, 0, 0],
        scale: [2.2, 2.2, 2.2],
        label: "维修顶灯",
        initiallyVisible: false,
        tags: ["official", "level01", "light", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_front_left",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [-5.2, 3.42, 5.6],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.38, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_front_right",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [5.2, 3.42, 5.6],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.38, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_mid_left",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [-5.2, 3.42, -1.8],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.38, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_mid_right",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [5.2, 3.42, -1.8],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.38, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_exit_left",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [-4.8, 3.42, -9.2],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.26, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_grid_exit_right",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_panel_maintenance",
        position: [4.8, 3.42, -9.2],
        rotation: [-1.5707963267948966, 0, 0],
        scale: [1.26, 1, 1],
        label: "维修天花板",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "configurable"],
      },
      {
        id: "level_01_ceiling_light_front_a",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_strip_light",
        position: [-4.8, 3.18, 4.2],
        rotation: [0, 0, 0],
        scale: [2.0, 1, 1],
        label: "维修天花灯",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "light", "configurable"],
      },
      {
        id: "level_01_ceiling_light_front_b",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_strip_light",
        position: [2.6, 3.18, 4.2],
        rotation: [0, 0, 0],
        scale: [2.0, 1, 1],
        label: "维修天花灯",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "light", "configurable"],
      },
      {
        id: "level_01_ceiling_light_mid_a",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_strip_light",
        position: [-2.8, 3.18, -2.1],
        rotation: [0, 0, 0],
        scale: [2.2, 1, 1],
        label: "维修天花灯",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "light", "configurable"],
      },
      {
        id: "level_01_ceiling_light_exit_a",
        roomId: "maintenance_bay_floor",
        modelKey: "room_ceiling_strip_light",
        position: [0, 3.18, -9.4],
        rotation: [0, 0, 0],
        scale: [2.2, 1, 1],
        label: "维修天花灯",
        initiallyVisible: false,
        tags: ["official", "level01", "ceiling_asset", "light", "configurable"],
      },
      {
        id: "level_01_supply_cabinet_left_spawn",
        roomId: "maintenance_bay_floor",
        modelKey: "room_maintenance_supply_cabinet",
        position: [-7.15, 0, 5.75],
        rotation: [0, 1.5707963267948966, 0],
        scale: 1.05,
        label: "维修柜",
        tags: ["official", "level01", "furniture", "configurable"],
      },
      {
        id: "level_01_supply_cabinet_right_mid",
        roomId: "maintenance_bay_floor",
        modelKey: "room_maintenance_supply_cabinet",
        position: [7.15, 0, 0.7],
        rotation: [0, -1.5707963267948966, 0],
        scale: 1.05,
        label: "维修柜",
        tags: ["official", "level01", "furniture", "configurable"],
      },
      {
        id: "level_01_utility_table_right_spawn",
        roomId: "maintenance_bay_floor",
        modelKey: "room_table_utility",
        position: [4.95, 0, 5.85],
        rotation: [0, -0.28, 0],
        scale: 1.08,
        label: "维修工具桌",
        tags: ["official", "level01", "furniture", "configurable"],
      },
      {
        id: "level_01_low_locker_left_mid",
        roomId: "maintenance_bay_floor",
        modelKey: "room_locker_low",
        position: [-7.25, 0, -2.2],
        rotation: [0, 1.5707963267948966, 0],
        scale: 1.1,
        label: "低矮工具柜",
        tags: ["official", "level01", "furniture", "configurable"],
      },
      {
        id: "level_01_low_locker_right_exit",
        roomId: "maintenance_bay_floor",
        modelKey: "room_locker_low",
        position: [7.05, 0, -7.8],
        rotation: [0, -1.5707963267948966, 0],
        scale: 1.1,
        label: "低矮工具柜",
        tags: ["official", "level01", "furniture", "configurable"],
      },
      {
        id: "level_01_terminal_wall_right_exit",
        roomId: "maintenance_bay_floor",
        modelKey: "room_terminal_wall",
        position: [8.45, 1.0, -4.15],
        rotation: [0, -1.5707963267948966, 0],
        scale: 1.05,
        label: "墙面终端",
        tags: ["official", "level01", "wall_equipment", "configurable"],
      },
      {
        id: "level_01_right_wall_big_screen",
        roomId: "maintenance_bay_floor",
        modelKey: "terminal_puzzle_big_screen",
        position: [8.45, 1.54, 3.15],
        rotation: [0, -1.5707963267948966, 0],
        scale: [1.05, 0.9, 0.92],
        label: "右墙监控屏",
        tags: ["official", "level01", "wall_equipment", "configurable"],
      },
      {
        id: "level_01_big_screen_back_wall",
        roomId: "maintenance_bay_floor",
        modelKey: "terminal_puzzle_big_screen",
        position: [0, 1.55, 8.72],
        rotation: [0, 0, 0],
        scale: [1.3, 1.05, 1],
        label: "维修监控屏",
        tags: ["official", "level01", "wall_equipment", "configurable"],
      },
      {
        id: "level_01_wall_medical_strip",
        roomId: "maintenance_bay_floor",
        modelKey: "light_wall_medical_strip_cyan_1m",
        position: [-8.6, 1.2, 3.1],
        rotation: [0, 1.5707963267948966, 0],
        scale: 1.35,
        label: "医疗灯条",
        tags: ["official", "level01", "light", "configurable"],
      },
    ],
    decals: [
      {
        id: "level_01_wall_human_body_reference",
        roomId: "maintenance_bay_floor",
        kind: "human_body_reference",
        position: [-4.65, 1.78, 4.55],
        size: [0.82, 1.22],
        opacity: 0.84,
        label: "人体比例参考",
        tags: ["official", "level01", "wall_reference", "configurable"],
      },
      {
        id: "level_01_wall_human_hand_reference",
        roomId: "maintenance_bay_floor",
        kind: "human_hand_reference",
        position: [-3.55, 1.86, 4.55],
        size: [0.72, 1.06],
        opacity: 0.84,
        label: "手部资产参考",
        tags: ["official", "level01", "wall_reference", "configurable"],
      },
      {
        id: "level_01_wall_human_spine_reference",
        roomId: "maintenance_bay_floor",
        kind: "human_spine_reference",
        position: [-2.62, 1.74, 4.55],
        size: [0.68, 1.0],
        opacity: 0.84,
        label: "脊柱映射参考",
        tags: ["official", "level01", "wall_reference", "configurable"],
      },
    ],
    navigation: {
      criticalPathRoomIds: ["maintenance_bay_floor", "level_01_tool_alcove", "service_elevator_room"],
      optionalRoomIds: [],
      maxBacktrackSeconds: 12,
      mobileReadableDoorCount: 2,
    },
  };
