import type { LevelPresentationConfig } from "../../schema/levelConfig";

export const level01Presentation: LevelPresentationConfig = {
    defaultWaveStartMessage: "维修单位正在部署。",
    reinforcementMessage: "增援维修单位已部署。",
    waveLabels: {
      first_contact: "初次接触",
      wave_01: "封锁响应",
      wave_02: "夹击波",
      elite_wave: "维修主管",
      exit_chase: "出口追击",
    },
    objectives: {
      upgrade: { title: "选一种活法", detail: "只能选一项", progressLabel: "升级上线", progressText: "选 1 个" },
      preRod: { title: "捡起铁棒", detail: "别空手" },
      prePistol: { title: "捡起手枪", detail: "拿到枪，门会锁" },
      default: { title: "逃出维修舱", detail: "广播在找你" },
      exitUnlocked: { title: "进电梯", detail: "别恋战", progressLabel: "撤离", progressText: "冲" },
    },
    flow: {
      title: {
        system: "异常生命信号",
        heading: "维修舱 01",
        body: "你在冷地板上醒来。灯一排排熄灭，门外有金属脚步。",
        signalStrip: ["生命体征", "出口门禁", "无线电噪声"],
        startButton: "进入维修舱",
      },
      death: {
        system: "急救失败",
        heading: "你倒下了",
        itchSuffix: "itch 版本无广告。",
        reviveOfferPrefix: "醒来后有几秒肾上腺素爆发。",
        cacheReadyText: "补给已备好。",
        reviveButtonRewarded: "看广告急救",
        reviveButtonLocal: "急救",
        restartButton: "重开本关",
        restartAfterReviveUsedButton: "重新开始",
      },
      transition: {
        system: "维修电梯",
        heading: "电梯下行",
      },
      victory: {
        system: "档案片段",
        heading: "档案涂黑",
        body: "电梯门合上，没有出口。屏幕只剩一句：对象仍在移动。下一层亮起了像公寓一样的白光。",
        doubleMemoryButton: "看广告 x2 积分",
        doubleMemoryClaimedButton: "x2 积分已领取",
        replayButton: "再次进入维修舱",
      },
    },
    waves: [
      {
        id: "first_contact",
        label: "初次接触",
        objectiveTitle: "逃出维修舱",
        objectiveDetail: "广播在找你",
        startMessage: "维修单位正在部署。",
        startWarning: { label: "逃出维修舱", detail: "广播在找你" },
        startWarningDuration: 2,
        startDialogueTrigger: "first_enemy_seen",
      },
      {
        id: "wave_01",
        label: "封锁响应",
        objectiveTitle: "守住配电成果",
        objectiveDetail: "供电恢复惊动了封锁队",
        startMessage: "维修单位正在部署。",
        startWarning: { label: "封锁响应", detail: "正面推进，别离工具间太远" },
        startWarningDuration: 2,
        startDialogueTrigger: "rear_enemy_spawned",
        startAudio: { key: "assist_reorient", intensity: 0.72 },
      },
      {
        id: "wave_02",
        label: "夹击波",
        objectiveTitle: "顶住夹击",
        objectiveDetail: "侧后方会来",
        startMessage: "维修单位正在部署。",
        startWarning: { label: "夹击波", detail: "侧后方的门也开了" },
        startWarningDuration: 2,
        startAudio: { key: "assist_reorient", intensity: 0.72 },
      },
      {
        id: "elite_wave",
        label: "维修主管",
        objectiveTitle: "击退主管",
        objectiveDetail: "别贴太久",
        startMessage: "维修主管正在接近。",
        startWarning: { label: "维修主管", detail: "近身危险" },
        startWarningDuration: 2,
        startDialogueTrigger: "elite_spawned",
        startAudio: { key: "elite_warning", intensity: 1.2 },
        startCamera: { shake: 0.5 },
      },
      {
        id: "exit_chase",
        label: "出口追击",
        objectiveTitle: "跑向电梯",
        objectiveDetail: "背后还有",
        startMessage: "维修单位正在部署。",
        startWarning: { label: "进电梯", detail: "边打边跑" },
        startWarningDuration: 2,
      },
    ],
    spawnSourceLabels: {
      front: "前方舱门",
      front_arc: "前方舱门",
      side_rear: "侧后方夹击",
      front_gate: "正门重型单位",
      turret_rail: "左右轨道炮台",
      around_ring: "四周维修通道",
      rear_ring: "后方追击队",
    },
    reinforcementWarningDuration: 1.45,
    environmentPressure: {
      title: 0.16,
      death: 0.95,
      idle: 0.24,
      exitUnlocked: 0.84,
      byWave: {
        first_contact: 0.34,
        wave_01: 0.55,
        wave_02: 0.74,
        elite_wave: 0.92,
        exit_chase: 1,
      },
    },
  };
