import type { CinematicBeatDefinition, CombatLimitConfig, EnemyDeathBeatConfig, LevelBossPhaseDefinition, LevelEnvironmentStateDefinition, SpawnGroupDefinition, WaveDefinition } from "../../schema/levelConfig";

export const level01Waves: readonly WaveDefinition[] = [
    {
      id: "first_contact",
      startDelay: 2.3,
      enemies: [{ archetype: "repair_drone", count: 1, from: "front" }],
      reward: "none",
    },
    {
      id: "wave_01",
      startDelay: 1.8,
      enemies: [
        { archetype: "repair_drone", count: 3, from: "front_arc" },
        { archetype: "clamp_bot", count: 1, from: "front" },
      ],
      reinforcements: [
        {
          archetype: "repair_drone",
          count: 1,
          from: "front_arc",
          startsAfter: 7,
          every: 9.5,
          maxGroups: 2,
          maxAlive: 3,
        },
      ],
      reward: "upgrade",
      completionDialogueTrigger: "wave_1_complete",
    },
    {
      id: "wave_02",
      startDelay: 2.1,
      enemies: [
        { archetype: "repair_drone", count: 4, from: "front_arc" },
        { archetype: "clamp_bot", count: 1, from: "side_rear" },
      ],
      reinforcements: [
        {
          archetype: "repair_drone",
          count: 1,
          from: "front_arc",
          startsAfter: 7,
          every: 9.5,
          maxGroups: 3,
          maxAlive: 4,
        },
        {
          archetype: "clamp_bot",
          count: 1,
          from: "side_rear",
          startsAfter: 14,
          every: 13,
          maxGroups: 2,
          maxAlive: 1,
        },
      ],
      reward: "none",
      completionDialogueTrigger: "wave_2_complete",
    },
    {
      id: "elite_wave",
      startDelay: 2.4,
      enemies: [
        {
          archetype: "custodian_elite",
          count: 1,
          from: "front_gate",
          tier: "leader",
          tierLabel: "维修头领",
          healthMultiplier: 0.54,
          damageMultiplier: 1.02,
          attackCooldownMultiplier: 1,
          radiusMultiplier: 1,
          visual: {
            modelKey: "hp_enemy_custodian_foreman_horror",
            coreColor: "#ff6a52",
            warningColor: "#ffd36d",
            textureAtlasKey: "custodian_boss",
            scaleMultiplier: 1.05,
            lightIntensityMultiplier: 1.18,
          },
        },
        { archetype: "repair_drone", count: 2, from: "front_arc" },
      ],
      reinforcements: [
        {
          archetype: "repair_drone",
          count: 1,
          from: "around_ring",
          startsAfter: 6,
          every: 8,
          maxGroups: 999,
          requiresEliteAlive: true,
          endless: true,
          maxAlive: 2,
        },
        {
          archetype: "clamp_bot",
          count: 1,
          from: "around_ring",
          startsAfter: 18,
          every: 15,
          maxGroups: 999,
          requiresEliteAlive: true,
          endless: true,
          maxAlive: 1,
        },
      ],
      reward: "none",
    },
    {
      id: "exit_chase",
      startDelay: 0.8,
      enemies: [
        { archetype: "repair_drone", count: 2, from: "side_rear" },
        { archetype: "clamp_bot", count: 1, from: "side_rear" },
      ],
      reinforcements: [
        {
          archetype: "repair_drone",
          count: 1,
          from: "rear_ring",
          startsAfter: 4,
          every: 6.5,
          maxGroups: 999,
          endless: true,
          maxAlive: 4,
        },
        {
          archetype: "clamp_bot",
          count: 1,
          from: "side_rear",
          startsAfter: 8,
          every: 9,
          maxGroups: 999,
          endless: true,
          maxAlive: 1,
        },
      ],
      reward: "open_exit",
      timedExitUnlockAfter: 12,
    },
  ];

export const level01EnvironmentStates: readonly LevelEnvironmentStateDefinition[] = [
    {
      id: "level_01_lights_on",
      label: "维修主照明",
      roomId: "maintenance_bay_floor",
      tintColor: "#d6fbff",
      glowColor: "#8df6ff",
      intensity: 0.72,
      opacity: 0.08,
    },
    {
      id: "level_01_lights_off",
      label: "应急低照明",
      roomId: "maintenance_bay_floor",
      tintColor: "#071018",
      glowColor: "#2e7584",
      intensity: 0.34,
      opacity: 0.16,
    },
    {
      id: "level_01_lockdown_dim",
      label: "维修封锁暗场",
      roomId: "maintenance_bay_floor",
      tintColor: "#07090b",
      glowColor: "#c68a52",
      intensity: 0.42,
      opacity: 0.045,
    },
    {
      id: "level_01_elevator_locked_red",
      label: "电梯锁定红灯",
      roomId: "service_elevator_room",
      tintColor: "#1d1110",
      glowColor: "#c17a48",
      intensity: 0.62,
      opacity: 0.07,
    },
    {
      id: "level_01_elevator_open_blue",
      label: "电梯开放蓝灯",
      roomId: "service_elevator_room",
      tintColor: "#0b2a33",
      glowColor: "#7ff2ff",
      intensity: 1.08,
      opacity: 0.2,
    },
  ];

export const level01BossPhases: readonly LevelBossPhaseDefinition[] = [
    {
      id: "level_01_elite_half_memory",
      actorId: "custodian_elite",
      tier: "leader",
      threshold: 0.5,
      actions: [
        { type: "queue_dialogue", trigger: "elite_hp_50" },
        { type: "camera_impact", cameraImpact: { shake: 0.38, fovKick: 1.8, rumble: 0.14, rumbleDuration: 0.18 } },
      ],
    },
  ];

export const level01SpawnGroups: readonly SpawnGroupDefinition[] = [
    { id: "front", label: "前方舱门", layout: "front" },
    { id: "front_arc", label: "前方舱门", layout: "front_arc" },
    { id: "side_rear", label: "侧后方夹击", layout: "side_rear" },
    { id: "front_gate", label: "正门重型单位", layout: "front_gate" },
    { id: "turret_rail", label: "左右轨道炮台", layout: "turret_rail" },
    { id: "around_ring", label: "四周维修通道", layout: "around_ring" },
    { id: "rear_ring", label: "后方追击队", layout: "rear_ring" },
  ];

export const level01CinematicBeats: readonly CinematicBeatDefinition[] = [
    {
      id: "wave_01_lockdown",
      waveId: "wave_01",
      triggerAt: 16,
      dialogueTrigger: "lockdown_started",
      spawnWarning: { label: "权限锁死", detail: "电梯断开。活下去" },
      spawnWarningDuration: 2.2,
      rewardPulse: { label: "维修封锁", detail: "门锁死了", rarity: "rare" },
      rewardPulseDuration: 1.55,
      cameraImpact: { shake: 0.45, fovKick: 2.8 },
      effects: [{ type: "dashBurst", position: [0, 0, -12.5], direction: [0, 0, 1], lifetime: 0.5, intensity: 2.1 }],
      audio: { key: "elite_warning", intensity: 0.78 },
    },
    {
      id: "wave_02_memory_flash",
      waveId: "wave_02",
      triggerAt: 18,
      dialogueTrigger: "memory_flash",
      spawnWarning: { label: "闪回", detail: "玻璃后，有影子抬头" },
      spawnWarningDuration: 2.25,
      rewardPulse: { label: "闪回", detail: "你见过这里", rarity: "story" },
      rewardPulseDuration: 1.65,
      cameraImpact: { shake: 0.54, fovKick: 3.4 },
      effects: [
        { type: "dashBurst", position: [-7.8, 0, -4], direction: [1, 0, 0.2], lifetime: 0.42, intensity: 1.7 },
        { type: "dashBurst", position: [7.8, 0, -4], direction: [-1, 0, 0.2], lifetime: 0.42, intensity: 1.7 },
      ],
      audio: { key: "assist_reorient", intensity: 0.9 },
    },
    {
      id: "wave_02_last_gate",
      waveId: "wave_02",
      triggerAt: 32,
      spawnWarning: { label: "出口线路亮了", detail: "撑过夹击" },
      spawnWarningDuration: 2.15,
      tempoSurgeSec: 4.2,
      cameraImpact: { shake: 0.5, fovKick: 2.6 },
      audio: { key: "ui_upgrade_select", intensity: 0.92 },
    },
    {
      id: "elite_title_slam",
      waveId: "elite_wave",
      triggerAt: 2.2,
      spawnWarning: { label: "维修主管", detail: "别被拖回台上" },
      spawnWarningDuration: 2.35,
      cameraImpact: { shake: 0.74, fovKick: 4 },
      audio: { key: "elite_warning", intensity: 1.22 },
    },
    {
      id: "elite_second_phase",
      waveId: "elite_wave",
      triggerAt: 34,
      spawnWarning: { label: "夹具入场", detail: "用电池开路" },
      spawnWarningDuration: 2.25,
      tempoSurgeSec: 3.8,
      cameraImpact: { shake: 0.58, fovKick: 3.2 },
      audio: { key: "weapon_shock_burst", intensity: 0.78 },
    },
    {
      id: "elite_final_push",
      waveId: "elite_wave",
      triggerAt: 58,
      spawnWarning: { label: "门快开了", detail: "准备跑" },
      spawnWarningDuration: 2.15,
      rewardPulse: { label: "逃生窗口", detail: "速度别断", rarity: "epic" },
      rewardPulseDuration: 1.6,
      tempoSurgeSec: 5.5,
      cameraImpact: { shake: 0.62, fovKick: 3.5 },
    },
    {
      id: "exit_chase_start",
      waveId: "exit_chase",
      triggerAt: 1,
      dialogueTrigger: "exit_chase_started",
      spawnWarning: { label: "跑", detail: "别恋战，进电梯" },
      spawnWarningDuration: 2.45,
      tempoSurgeSec: 4,
      cameraImpact: { shake: 0.55, fovKick: 3.2 },
      effects: [{ type: "dashBurst", position: [0, 0, 7.2], direction: [0, 0, -1], lifetime: 0.55, intensity: 2.4 }],
      audio: { key: "elite_warning", intensity: 0.95 },
    },
  ];

export const level01CombatLimits: CombatLimitConfig = {
    smallEnemyArchetypes: ["repair_drone", "clamp_bot"],
    eliteArchetypeId: "custodian_elite",
    smallEnemyDamageMultiplier: 1.3,
  };

export const level01EnemyDeathBeats: readonly EnemyDeathBeatConfig[] = [
    {
      archetypeId: "custodian_elite",
      spawnWarning: {
        label: "维修主管倒下",
        detail: "地面在震：冲向维修电梯",
      },
      spawnWarningDuration: 2.4,
      cameraImpact: { shake: 1.15, fovKick: 6.2, rumble: 0.85, rumbleDuration: 0.85 },
      dashBurst: { lifetime: 0.62, intensity: 2.8 },
    },
  ];
