// AUTO-GENERATED by scripts/asset-build/generate-builder-asset-pack-registry.mjs — DO NOT EDIT.
// Regenerate: node scripts/asset-build/generate-builder-asset-pack-registry.mjs --emit
// Source packs: hp_builder_desire_pack_v1, hp_cyberpunk_batch01_v1, hp_l2_cc0_domestic_polyhaven_v1, hp_level01_furniture_image2_v1, hp_level01_power_infra_image2_v1, hp_level01_safety_storage_image2_v1, hp_level01_workcell_image2_v1, hp_level02_furniture_image2_v1, hp_level03_furniture_image2_v1, hp_level04_memory_clinic_furniture_v1, hp_level05_furniture_image2_v1, hp_level05_reclamation_dressing_v4, hp_level05_reclamation_furniture_image2_v3_batch02, hp_level05_reclamation_furniture_image2_v3_batch03, hp_level05_reclamation_furniture_image2_v3_batch04, hp_level05_reclamation_furniture_image2_v3_hero, hp_official_remaster_batch01_v1, hp_residential_reference_furniture_image2_v1
import type { EnvironmentModelRegistry } from "./types";

import glbUrl0 from "../../models-cooked/environment/props/hp_furniture_residential_cleaner_closet_v1.glb?url";
import glbUrl1 from "../../models-cooked/environment/props/hp_furniture_residential_entry_bench_cubby_v1.glb?url";
import glbUrl2 from "../../models-cooked/environment/props/hp_furniture_residential_fluted_sideboard_v1.glb?url";
import glbUrl3 from "../../models-cooked/environment/props/hp_furniture_residential_oval_coffee_table_v1.glb?url";
import glbUrl4 from "../../models-cooked/environment/props/hp_furniture_residential_room_divider_shelf_v1.glb?url";
import glbUrl5 from "../../models-cooked/environment/level02-cc0-domestic/hp_l2_cc0_ceiling_lamp_polyhaven_v1.glb?url";
import glbUrl6 from "../../models-cooked/environment/level02-cc0-domestic/hp_l2_cc0_desk_lamp_polyhaven_v1.glb?url";
import glbUrl7 from "../../models-cooked/environment/level02-cc0-domestic/hp_l2_cc0_dining_chair_polyhaven_v1.glb?url";
import glbUrl8 from "../../models-cooked/environment/level02-cc0-domestic/hp_l2_cc0_ottoman_polyhaven_v1.glb?url";
import glbUrl9 from "../../models-cooked/environment/level02-cc0-domestic/hp_l2_cc0_wall_mirror_polyhaven_v1.glb?url";
import glbUrl10 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_cable_trolley.glb?url";
import glbUrl11 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_decon_gate.glb?url";
import glbUrl12 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_exam_table.glb?url";
import glbUrl13 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_lime_ottoman.glb?url";
import glbUrl14 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_med_cabinet.glb?url";
import glbUrl15 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_memory_recliner.glb?url";
import glbUrl16 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_monitor_arm.glb?url";
import glbUrl17 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_observation_desk.glb?url";
import glbUrl18 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_privacy_screen.glb?url";
import glbUrl19 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_projection_pod.glb?url";
import glbUrl20 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_reception_counter.glb?url";
import glbUrl21 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_record_wall_cabinet.glb?url";
import glbUrl22 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_rescue_speaker_panel.glb?url";
import glbUrl23 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_scan_arch.glb?url";
import glbUrl24 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_sedation_gate.glb?url";
import glbUrl25 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_side_table_planter.glb?url";
import glbUrl26 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_surgical_light.glb?url";
import glbUrl27 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_theater_wall.glb?url";
import glbUrl28 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_triage_kiosk.glb?url";
import glbUrl29 from "../../models-cooked/environment/level04-memory-clinic-furniture-v1/hp_l4_cineclinic_waiting_sofa_row.glb?url";
import glbUrl30 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_cable_pit_cover.glb?url";
import glbUrl31 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_cable_trunk.glb?url";
import glbUrl32 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_camera_cluster.glb?url";
import glbUrl33 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_core_power_spine.glb?url";
import glbUrl34 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_cryo_column.glb?url";
import glbUrl35 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_drone_cradle.glb?url";
import glbUrl36 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_evidence_vitrine.glb?url";
import glbUrl37 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_gate_turnstile.glb?url";
import glbUrl38 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_hazard_barrier.glb?url";
import glbUrl39 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_holo_pylon.glb?url";
import glbUrl40 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_interrogation_chair.glb?url";
import glbUrl41 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_kitchen_lab_island.glb?url";
import glbUrl42 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_monitor_wall.glb?url";
import glbUrl43 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_mural_circuit_city.glb?url";
import glbUrl44 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_mural_eye_array.glb?url";
import glbUrl45 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_mural_family_glitch.glb?url";
import glbUrl46 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_mural_protocol_finale.glb?url";
import glbUrl47 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_operating_pod.glb?url";
import glbUrl48 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_organ_printer.glb?url";
import glbUrl49 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_pipe_manifold.glb?url";
import glbUrl50 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_security_desk.glb?url";
import glbUrl51 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_sensor_plant.glb?url";
import glbUrl52 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_server_rack.glb?url";
import glbUrl53 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_smart_bed_pod.glb?url";
import glbUrl54 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_substation_console.glb?url";
import glbUrl55 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_tv_shrine.glb?url";
import glbUrl56 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_uplink_throne.glb?url";
import glbUrl57 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_valve_cluster.glb?url";
import glbUrl58 from "../../models-cooked/environment/hp-cyberpunk-batch01/hp_room_cyber_vending_unit.glb?url";
import glbUrl59 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_archive_desk.glb?url";
import glbUrl60 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_archive_tower.glb?url";
import glbUrl61 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_bed_pod.glb?url";
import glbUrl62 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_brass_safe.glb?url";
import glbUrl63 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_card_catalog.glb?url";
import glbUrl64 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_clue_board.glb?url";
import glbUrl65 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_evidence_cluster.glb?url";
import glbUrl66 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_gallery_bench.glb?url";
import glbUrl67 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_holo_globe.glb?url";
import glbUrl68 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_leather_chair.glb?url";
import glbUrl69 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_light_gantry.glb?url";
import glbUrl70 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_low_bookcase.glb?url";
import glbUrl71 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_portrait_panel.glb?url";
import glbUrl72 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_security_console.glb?url";
import glbUrl73 from "../../models-cooked/environment/hp-builder-desire-pack01/hp_room_desire_tall_vitrine.glb?url";
import glbUrl74 from "../../models-cooked/environment/level01-safety-storage-image2/room_l1_img2_access_diagnostic_cabinet.glb?url";
import glbUrl75 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_battery_cart.glb?url";
import glbUrl76 from "../../models-cooked/environment/level01-power-infra-image2/room_l1_img2_battery_charging_rack.glb?url";
import glbUrl77 from "../../models-cooked/environment/level01-safety-storage-image2/room_l1_img2_body_reference_lightbox.glb?url";
import glbUrl78 from "../../models-cooked/environment/level01-power-infra-image2/room_l1_img2_breaker_pylon.glb?url";
import glbUrl79 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_cable_reel_cart.glb?url";
import glbUrl80 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_ceiling_service_light.glb?url";
import glbUrl81 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_diagnostic_locker.glb?url";
import glbUrl82 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_folded_gurney.glb?url";
import glbUrl83 from "../../models-cooked/environment/level01-workcell-image2/room_l1_img2_hydraulic_lift_table.glb?url";
import glbUrl84 from "../../models-cooked/environment/level01-safety-storage-image2/room_l1_img2_maintenance_privacy_screen.glb?url";
import glbUrl85 from "../../models-cooked/environment/level01-workcell-image2/room_l1_img2_mobile_repair_cart.glb?url";
import glbUrl86 from "../../models-cooked/environment/level01-power-infra-image2/room_l1_img2_overhead_rail_gantry.glb?url";
import glbUrl87 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_parts_cabinet.glb?url";
import glbUrl88 from "../../models-cooked/environment/level01-safety-storage-image2/room_l1_img2_parts_tote_stack.glb?url";
import glbUrl89 from "../../models-cooked/environment/level01-workcell-image2/room_l1_img2_prosthetic_parts_cabinet.glb?url";
import glbUrl90 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_repair_workbench.glb?url";
import glbUrl91 from "../../models-cooked/environment/level01-power-infra-image2/room_l1_img2_robot_docking_post.glb?url";
import glbUrl92 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_service_stool.glb?url";
import glbUrl93 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_sterile_tool_rack.glb?url";
import glbUrl94 from "../../models-cooked/environment/level01-workcell-image2/room_l1_img2_sterile_wash_basin.glb?url";
import glbUrl95 from "../../models-cooked/environment/level01-furniture-image2/room_l1_img2_utility_crate.glb?url";
import glbUrl96 from "../../models-cooked/environment/level01-power-infra-image2/room_l1_img2_valve_manifold_wall.glb?url";
import glbUrl97 from "../../models-cooked/environment/level01-workcell-image2/room_l1_img2_wall_tool_board.glb?url";
import glbUrl98 from "../../models-cooked/environment/level01-safety-storage-image2/room_l1_img2_warning_barrier.glb?url";
import glbUrl99 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_camera_lamp.glb?url";
import glbUrl100 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_carekeeper_armchair.glb?url";
import glbUrl101 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_family_portrait_console.glb?url";
import glbUrl102 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_living_end_elevator_fixture.glb?url";
import glbUrl103 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_modular_sofa.glb?url";
import glbUrl104 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_nursery_bed.glb?url";
import glbUrl105 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_observation_bookshelf.glb?url";
import glbUrl106 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_observation_dining_table.glb?url";
import glbUrl107 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_scanner_wardrobe.glb?url";
import glbUrl108 from "../../models-cooked/environment/level02-furniture-image2/room_l2_img2_service_kitchen_counter.glb?url";
import glbUrl109 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_archive_card_cabinet.glb?url";
import glbUrl110 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_display_plinth.glb?url";
import glbUrl111 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_evidence_round_table.glb?url";
import glbUrl112 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_label_terminal.glb?url";
import glbUrl113 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_mural_lightbox.glb?url";
import glbUrl114 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_preservation_case.glb?url";
import glbUrl115 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_queue_rail.glb?url";
import glbUrl116 from "../../models-cooked/environment/level03-furniture-image2/room_l3_img2_specimen_bench.glb?url";
import glbUrl117 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_archive_server_column.glb?url";
import glbUrl118 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_biometric_filing_throne.glb?url";
import glbUrl119 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_core_memory_altar.glb?url";
import glbUrl120 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_data_spine_rack.glb?url";
import glbUrl121 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_heavy_archive_elevator_door.glb?url";
import glbUrl122 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_identity_capsule_cabinet.glb?url";
import glbUrl123 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_lockbox_pedestal.glb?url";
import glbUrl124 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_retrieval_conveyor_table.glb?url";
import glbUrl125 from "../../models-cooked/environment/level05-furniture-image2/room_l5_img2_route_key_pedestal.glb?url";
import glbUrl126 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch02/room_l5_v3_anemone_lounge_chair.glb?url";
import glbUrl127 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch03/room_l5_v3_bio_recline_couch.glb?url";
import glbUrl128 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch03/room_l5_v3_cleaning_robot_dock.glb?url";
import glbUrl129 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-hero/room_l5_v3_core_route_map_table.glb?url";
import glbUrl130 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch04/room_l5_v3_corner_privacy_screen.glb?url";
import glbUrl131 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch02/room_l5_v3_crescent_low_sofa.glb?url";
import glbUrl132 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch04/room_l5_v3_curved_archive_shelf.glb?url";
import glbUrl133 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch02/room_l5_v3_evidence_coffee_table.glb?url";
import glbUrl134 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch04/room_l5_v3_hanging_cable_organizer.glb?url";
import glbUrl135 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch02/room_l5_v3_human_archive_cabinet.glb?url";
import glbUrl136 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-hero/room_l5_v3_intake_identity_gate.glb?url";
import glbUrl137 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch03/room_l5_v3_limb_calibration_rack.glb?url";
import glbUrl138 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch03/room_l5_v3_memory_diagnostic_terminal.glb?url";
import glbUrl139 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-hero/room_l5_v3_reclamation_core_altar.glb?url";
import glbUrl140 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-hero/room_l5_v3_release_key_vault.glb?url";
import glbUrl141 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch02/room_l5_v3_service_side_console.glb?url";
import glbUrl142 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch04/room_l5_v3_specimen_drawer_stack.glb?url";
import glbUrl143 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch04/room_l5_v3_surgical_light_stand.glb?url";
import glbUrl144 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-hero/room_l5_v3_three_lock_monolith.glb?url";
import glbUrl145 from "../../models-cooked/environment/level05-reclamation-furniture-image2-v3-batch03/room_l5_v3_tissue_freezer_cabinet.glb?url";
import glbUrl146 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_ceiling_cable_tray.glb?url";
import glbUrl147 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_ceiling_service_lamp.glb?url";
import glbUrl148 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_clamp_relay_column.glb?url";
import glbUrl149 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_floor_cable_bridge.glb?url";
import glbUrl150 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_maintenance_crate_stack.glb?url";
import glbUrl151 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_sample_canister_rack.glb?url";
import glbUrl152 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_wall_pipe_manifold.glb?url";
import glbUrl153 from "../../models-cooked/environment/level05-reclamation-dressing-v4/room_l5_v4_warning_beacon_pylon.glb?url";
import glbUrl154 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_diagnosis_terminal.glb?url";
import glbUrl155 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_dosage_cart.glb?url";
import glbUrl156 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_eye_lightbox.glb?url";
import glbUrl157 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_memory_projector.glb?url";
import glbUrl158 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_sedation_gate.glb?url";
import glbUrl159 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_surgical_curtain.glb?url";
import glbUrl160 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_therapy_chair.glb?url";
import glbUrl161 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_clinic_waiting_row.glb?url";
import glbUrl162 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_arena_marker.glb?url";
import glbUrl163 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_conveyor_segment.glb?url";
import glbUrl164 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_coolant_manifold.glb?url";
import glbUrl165 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_final_lock_column.glb?url";
import glbUrl166 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_identity_server.glb?url";
import glbUrl167 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_incinerator_hatch.glb?url";
import glbUrl168 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_reclamation_altar.glb?url";
import glbUrl169 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_core_warning_pylon.glb?url";
import glbUrl170 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_crib_monitor.glb?url";
import glbUrl171 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_family_table.glb?url";
import glbUrl172 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_intercom_panel.glb?url";
import glbUrl173 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_kitchen_fake.glb?url";
import glbUrl174 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_observation_sofa.glb?url";
import glbUrl175 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_photo_cluster.glb?url";
import glbUrl176 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_tv_shrine_broken.glb?url";
import glbUrl177 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_home_wall_rupture.glb?url";
import glbUrl178 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_battery_rack.glb?url";
import glbUrl179 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_broken_cradle.glb?url";
import glbUrl180 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_cable_spine.glb?url";
import glbUrl181 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_coolant_drums.glb?url";
import glbUrl182 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_door_console.glb?url";
import glbUrl183 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_gantry_hoist.glb?url";
import glbUrl184 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_tool_wall.glb?url";
import glbUrl185 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_maint_weapon_cradle.glb?url";
import glbUrl186 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_archive_plinth.glb?url";
import glbUrl187 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_audio_stand.glb?url";
import glbUrl188 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_body_display.glb?url";
import glbUrl189 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_curator_desk.glb?url";
import glbUrl190 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_restoration_bench.glb?url";
import glbUrl191 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_route_inlay.glb?url";
import glbUrl192 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_specimen_case.glb?url";
import glbUrl193 from "../../models-cooked/environment/hp-official-remaster-batch01/hp_room_rm_museum_stanchion.glb?url";

export const generatedBuilderPackEnvironmentModelAssets = {
  hp_furniture_residential_cleaner_closet_v1: {
    modelKey: "hp_furniture_residential_cleaner_closet_v1",
    url: glbUrl0,
    category: "room",
    sizeMeters: [0.93, 1.96, 0.62],
  },
  hp_furniture_residential_entry_bench_cubby_v1: {
    modelKey: "hp_furniture_residential_entry_bench_cubby_v1",
    url: glbUrl1,
    category: "room",
    sizeMeters: [1.52, 1.64, 0.588],
  },
  hp_furniture_residential_fluted_sideboard_v1: {
    modelKey: "hp_furniture_residential_fluted_sideboard_v1",
    url: glbUrl2,
    category: "room",
    sizeMeters: [1.86, 0.962, 0.668],
  },
  hp_furniture_residential_oval_coffee_table_v1: {
    modelKey: "hp_furniture_residential_oval_coffee_table_v1",
    url: glbUrl3,
    category: "room",
    sizeMeters: [1.48, 0.477, 0.82],
  },
  hp_furniture_residential_room_divider_shelf_v1: {
    modelKey: "hp_furniture_residential_room_divider_shelf_v1",
    url: glbUrl4,
    category: "room",
    sizeMeters: [1.72, 1.32, 0.384],
  },
  hp_l2_cc0_ceiling_lamp_polyhaven_v1: {
    modelKey: "hp_l2_cc0_ceiling_lamp_polyhaven_v1",
    url: glbUrl5,
    category: "room",
    sizeMeters: [0.39, 0.928, 0.39],
  },
  hp_l2_cc0_desk_lamp_polyhaven_v1: {
    modelKey: "hp_l2_cc0_desk_lamp_polyhaven_v1",
    url: glbUrl6,
    category: "room",
    sizeMeters: [0.163, 0.72, 0.495],
  },
  hp_l2_cc0_dining_chair_polyhaven_v1: {
    modelKey: "hp_l2_cc0_dining_chair_polyhaven_v1",
    url: glbUrl7,
    category: "room",
    sizeMeters: [0.428, 0.96, 0.605],
  },
  hp_l2_cc0_ottoman_polyhaven_v1: {
    modelKey: "hp_l2_cc0_ottoman_polyhaven_v1",
    url: glbUrl8,
    category: "room",
    sizeMeters: [0.652, 0.46, 0.471],
  },
  hp_l2_cc0_wall_mirror_polyhaven_v1: {
    modelKey: "hp_l2_cc0_wall_mirror_polyhaven_v1",
    url: glbUrl9,
    category: "room",
    sizeMeters: [0.798, 1.22, 0.153],
  },
  hp_l4_cineclinic_cable_trolley: {
    modelKey: "hp_l4_cineclinic_cable_trolley",
    url: glbUrl10,
    category: "room",
    sizeMeters: [0.82, 1.36, 0.68],
  },
  hp_l4_cineclinic_decon_gate: {
    modelKey: "hp_l4_cineclinic_decon_gate",
    url: glbUrl11,
    category: "room",
    sizeMeters: [2.65, 2.62, 0.72],
  },
  hp_l4_cineclinic_exam_table: {
    modelKey: "hp_l4_cineclinic_exam_table",
    url: glbUrl12,
    category: "room",
    sizeMeters: [2.28, 1.18, 0.92],
  },
  hp_l4_cineclinic_lime_ottoman: {
    modelKey: "hp_l4_cineclinic_lime_ottoman",
    url: glbUrl13,
    category: "room",
    sizeMeters: [0.86, 0.48, 0.86],
  },
  hp_l4_cineclinic_med_cabinet: {
    modelKey: "hp_l4_cineclinic_med_cabinet",
    url: glbUrl14,
    category: "room",
    sizeMeters: [1.05, 1.94, 0.52],
  },
  hp_l4_cineclinic_memory_recliner: {
    modelKey: "hp_l4_cineclinic_memory_recliner",
    url: glbUrl15,
    category: "room",
    sizeMeters: [1.42, 1.48, 1.82],
  },
  hp_l4_cineclinic_monitor_arm: {
    modelKey: "hp_l4_cineclinic_monitor_arm",
    url: glbUrl16,
    category: "room",
    sizeMeters: [2.18, 1.78, 0.72],
  },
  hp_l4_cineclinic_observation_desk: {
    modelKey: "hp_l4_cineclinic_observation_desk",
    url: glbUrl17,
    category: "room",
    sizeMeters: [1.72, 1.34, 1.16],
  },
  hp_l4_cineclinic_privacy_screen: {
    modelKey: "hp_l4_cineclinic_privacy_screen",
    url: glbUrl18,
    category: "room",
    sizeMeters: [1.86, 1.92, 0.32],
  },
  hp_l4_cineclinic_projection_pod: {
    modelKey: "hp_l4_cineclinic_projection_pod",
    url: glbUrl19,
    category: "room",
    sizeMeters: [0.98, 1.42, 1.26],
  },
  hp_l4_cineclinic_reception_counter: {
    modelKey: "hp_l4_cineclinic_reception_counter",
    url: glbUrl20,
    category: "room",
    sizeMeters: [3.2, 1.28, 0.86],
  },
  hp_l4_cineclinic_record_wall_cabinet: {
    modelKey: "hp_l4_cineclinic_record_wall_cabinet",
    url: glbUrl21,
    category: "room",
    sizeMeters: [1.34, 1.36, 0.42],
  },
  hp_l4_cineclinic_rescue_speaker_panel: {
    modelKey: "hp_l4_cineclinic_rescue_speaker_panel",
    url: glbUrl22,
    category: "room",
    sizeMeters: [1.24, 0.72, 0.12],
  },
  hp_l4_cineclinic_scan_arch: {
    modelKey: "hp_l4_cineclinic_scan_arch",
    url: glbUrl23,
    category: "room",
    sizeMeters: [1.96, 2.05, 0.82],
  },
  hp_l4_cineclinic_sedation_gate: {
    modelKey: "hp_l4_cineclinic_sedation_gate",
    url: glbUrl24,
    category: "room",
    sizeMeters: [1.92, 2.36, 0.72],
  },
  hp_l4_cineclinic_side_table_planter: {
    modelKey: "hp_l4_cineclinic_side_table_planter",
    url: glbUrl25,
    category: "room",
    sizeMeters: [0.86, 0.82, 0.72],
  },
  hp_l4_cineclinic_surgical_light: {
    modelKey: "hp_l4_cineclinic_surgical_light",
    url: glbUrl26,
    category: "room",
    sizeMeters: [1.06, 1.22, 0.92],
  },
  hp_l4_cineclinic_theater_wall: {
    modelKey: "hp_l4_cineclinic_theater_wall",
    url: glbUrl27,
    category: "room",
    sizeMeters: [5.05, 2.32, 0.42],
  },
  hp_l4_cineclinic_triage_kiosk: {
    modelKey: "hp_l4_cineclinic_triage_kiosk",
    url: glbUrl28,
    category: "room",
    sizeMeters: [0.78, 1.56, 0.58],
  },
  hp_l4_cineclinic_waiting_sofa_row: {
    modelKey: "hp_l4_cineclinic_waiting_sofa_row",
    url: glbUrl29,
    category: "room",
    sizeMeters: [2.55, 0.88, 0.82],
  },
  room_cyber_cable_pit_cover: {
    modelKey: "room_cyber_cable_pit_cover",
    url: glbUrl30,
    category: "room",
    sizeMeters: [1.3, 0.185, 0.91],
  },
  room_cyber_cable_trunk: {
    modelKey: "room_cyber_cable_trunk",
    url: glbUrl31,
    category: "room",
    sizeMeters: [2.871, 0.22, 1.059],
  },
  room_cyber_camera_cluster: {
    modelKey: "room_cyber_camera_cluster",
    url: glbUrl32,
    category: "room",
    sizeMeters: [0.512, 0.527, 0.615],
  },
  room_cyber_core_power_spine: {
    modelKey: "room_cyber_core_power_spine",
    url: glbUrl33,
    category: "room",
    sizeMeters: [1.1, 2.8, 1.1],
  },
  room_cyber_cryo_column: {
    modelKey: "room_cyber_cryo_column",
    url: glbUrl34,
    category: "room",
    sizeMeters: [1.287, 2.36, 1.1],
  },
  room_cyber_drone_cradle: {
    modelKey: "room_cyber_drone_cradle",
    url: glbUrl35,
    category: "room",
    sizeMeters: [1.5, 1.635, 1.3],
  },
  room_cyber_evidence_vitrine: {
    modelKey: "room_cyber_evidence_vitrine",
    url: glbUrl36,
    category: "room",
    sizeMeters: [1.2, 1.52, 1],
  },
  room_cyber_gate_turnstile: {
    modelKey: "room_cyber_gate_turnstile",
    url: glbUrl37,
    category: "room",
    sizeMeters: [1.6, 1.31, 1],
  },
  room_cyber_hazard_barrier: {
    modelKey: "room_cyber_hazard_barrier",
    url: glbUrl38,
    category: "room",
    sizeMeters: [1.9, 1.173, 0.6],
  },
  room_cyber_holo_pylon: {
    modelKey: "room_cyber_holo_pylon",
    url: glbUrl39,
    category: "room",
    sizeMeters: [1, 2.05, 1],
  },
  room_cyber_interrogation_chair: {
    modelKey: "room_cyber_interrogation_chair",
    url: glbUrl40,
    category: "room",
    sizeMeters: [1.215, 1.946, 1.3],
  },
  room_cyber_kitchen_lab_island: {
    modelKey: "room_cyber_kitchen_lab_island",
    url: glbUrl41,
    category: "room",
    sizeMeters: [2, 1.3, 1.2],
  },
  room_cyber_monitor_wall: {
    modelKey: "room_cyber_monitor_wall",
    url: glbUrl42,
    category: "room",
    sizeMeters: [2.6, 2, 1],
  },
  room_cyber_mural_circuit_city: {
    modelKey: "room_cyber_mural_circuit_city",
    url: glbUrl43,
    category: "room",
    sizeMeters: [2.28, 1.37, 0.122],
  },
  room_cyber_mural_eye_array: {
    modelKey: "room_cyber_mural_eye_array",
    url: glbUrl44,
    category: "room",
    sizeMeters: [1.98, 1.245, 0.12],
  },
  room_cyber_mural_family_glitch: {
    modelKey: "room_cyber_mural_family_glitch",
    url: glbUrl45,
    category: "room",
    sizeMeters: [2.068, 1.24, 0.112],
  },
  room_cyber_mural_protocol_finale: {
    modelKey: "room_cyber_mural_protocol_finale",
    url: glbUrl46,
    category: "room",
    sizeMeters: [2.48, 1.45, 0.115],
  },
  room_cyber_operating_pod: {
    modelKey: "room_cyber_operating_pod",
    url: glbUrl47,
    category: "room",
    sizeMeters: [1.6, 1.79, 2.4],
  },
  room_cyber_organ_printer: {
    modelKey: "room_cyber_organ_printer",
    url: glbUrl48,
    category: "room",
    sizeMeters: [1.1, 2.2, 1.12],
  },
  room_cyber_pipe_manifold: {
    modelKey: "room_cyber_pipe_manifold",
    url: glbUrl49,
    category: "room",
    sizeMeters: [1.6, 1.5, 0.36],
  },
  room_cyber_security_desk: {
    modelKey: "room_cyber_security_desk",
    url: glbUrl50,
    category: "room",
    sizeMeters: [2.2, 1.328, 1.3],
  },
  room_cyber_sensor_plant: {
    modelKey: "room_cyber_sensor_plant",
    url: glbUrl51,
    category: "room",
    sizeMeters: [0.7, 1.103, 0.7],
  },
  room_cyber_server_rack: {
    modelKey: "room_cyber_server_rack",
    url: glbUrl52,
    category: "room",
    sizeMeters: [0.9, 2.18, 1.15],
  },
  room_cyber_smart_bed_pod: {
    modelKey: "room_cyber_smart_bed_pod",
    url: glbUrl53,
    category: "room",
    sizeMeters: [1.461, 1.291, 2.316],
  },
  room_cyber_substation_console: {
    modelKey: "room_cyber_substation_console",
    url: glbUrl54,
    category: "room",
    sizeMeters: [1.9, 1.862, 1.2],
  },
  room_cyber_tv_shrine: {
    modelKey: "room_cyber_tv_shrine",
    url: glbUrl55,
    category: "room",
    sizeMeters: [2.2, 1.53, 1.044],
  },
  room_cyber_uplink_throne: {
    modelKey: "room_cyber_uplink_throne",
    url: glbUrl56,
    category: "room",
    sizeMeters: [2.114, 2.681, 1.763],
  },
  room_cyber_valve_cluster: {
    modelKey: "room_cyber_valve_cluster",
    url: glbUrl57,
    category: "room",
    sizeMeters: [1.4, 1.277, 1],
  },
  room_cyber_vending_unit: {
    modelKey: "room_cyber_vending_unit",
    url: glbUrl58,
    category: "room",
    sizeMeters: [1.1, 1.96, 0.9],
  },
  room_desire_archive_desk: {
    modelKey: "room_desire_archive_desk",
    url: glbUrl59,
    category: "room",
    sizeMeters: [2, 1.136, 1.1],
  },
  room_desire_archive_tower: {
    modelKey: "room_desire_archive_tower",
    url: glbUrl60,
    category: "room",
    sizeMeters: [1, 2.25, 1],
  },
  room_desire_bed_pod: {
    modelKey: "room_desire_bed_pod",
    url: glbUrl61,
    category: "room",
    sizeMeters: [2.23, 1.336, 1.2],
  },
  room_desire_brass_safe: {
    modelKey: "room_desire_brass_safe",
    url: glbUrl62,
    category: "room",
    sizeMeters: [1.05, 1.06, 0.957],
  },
  room_desire_card_catalog: {
    modelKey: "room_desire_card_catalog",
    url: glbUrl63,
    category: "room",
    sizeMeters: [1.3, 1.6, 0.81],
  },
  room_desire_clue_board: {
    modelKey: "room_desire_clue_board",
    url: glbUrl64,
    category: "room",
    sizeMeters: [1.5, 1.115, 0.115],
  },
  room_desire_evidence_cluster: {
    modelKey: "room_desire_evidence_cluster",
    url: glbUrl65,
    category: "room",
    sizeMeters: [0.85, 0.88, 0.85],
  },
  room_desire_gallery_bench: {
    modelKey: "room_desire_gallery_bench",
    url: glbUrl66,
    category: "room",
    sizeMeters: [1.7, 0.52, 0.7],
  },
  room_desire_holo_globe: {
    modelKey: "room_desire_holo_globe",
    url: glbUrl67,
    category: "room",
    sizeMeters: [0.8, 1.479, 0.8],
  },
  room_desire_leather_chair: {
    modelKey: "room_desire_leather_chair",
    url: glbUrl68,
    category: "room",
    sizeMeters: [0.95, 1.1, 0.95],
  },
  room_desire_light_gantry: {
    modelKey: "room_desire_light_gantry",
    url: glbUrl69,
    category: "room",
    sizeMeters: [2.4, 2.32, 0.5],
  },
  room_desire_low_bookcase: {
    modelKey: "room_desire_low_bookcase",
    url: glbUrl70,
    category: "room",
    sizeMeters: [2.3, 1.142, 0.6],
  },
  room_desire_portrait_panel: {
    modelKey: "room_desire_portrait_panel",
    url: glbUrl71,
    category: "room",
    sizeMeters: [0.92, 1.37, 0.225],
  },
  room_desire_security_console: {
    modelKey: "room_desire_security_console",
    url: glbUrl72,
    category: "room",
    sizeMeters: [1.45, 1.193, 0.95],
  },
  room_desire_tall_vitrine: {
    modelKey: "room_desire_tall_vitrine",
    url: glbUrl73,
    category: "room",
    sizeMeters: [1.05, 1.965, 1.05],
  },
  room_l1_img2_access_diagnostic_cabinet: {
    modelKey: "room_l1_img2_access_diagnostic_cabinet",
    url: glbUrl74,
    category: "room",
    sizeMeters: [0.86, 1.65, 0.742],
  },
  room_l1_img2_battery_cart: {
    modelKey: "room_l1_img2_battery_cart",
    url: glbUrl75,
    category: "room",
    sizeMeters: [0.9, 0.925, 0.66],
  },
  room_l1_img2_battery_charging_rack: {
    modelKey: "room_l1_img2_battery_charging_rack",
    url: glbUrl76,
    category: "room",
    sizeMeters: [1.45, 1.67, 0.662],
  },
  room_l1_img2_body_reference_lightbox: {
    modelKey: "room_l1_img2_body_reference_lightbox",
    url: glbUrl77,
    category: "room",
    sizeMeters: [1.175, 1.44, 0.158],
  },
  room_l1_img2_breaker_pylon: {
    modelKey: "room_l1_img2_breaker_pylon",
    url: glbUrl78,
    category: "room",
    sizeMeters: [0.8, 1.745, 0.72],
  },
  room_l1_img2_cable_reel_cart: {
    modelKey: "room_l1_img2_cable_reel_cart",
    url: glbUrl79,
    category: "room",
    sizeMeters: [1.08, 0.917, 0.72],
  },
  room_l1_img2_ceiling_service_light: {
    modelKey: "room_l1_img2_ceiling_service_light",
    url: glbUrl80,
    category: "room",
    sizeMeters: [0.9, 0.225, 0.9],
  },
  room_l1_img2_diagnostic_locker: {
    modelKey: "room_l1_img2_diagnostic_locker",
    url: glbUrl81,
    category: "room",
    sizeMeters: [0.7, 2, 0.649],
  },
  room_l1_img2_folded_gurney: {
    modelKey: "room_l1_img2_folded_gurney",
    url: glbUrl82,
    category: "room",
    sizeMeters: [2.2, 0.9, 0.749],
  },
  room_l1_img2_hydraulic_lift_table: {
    modelKey: "room_l1_img2_hydraulic_lift_table",
    url: glbUrl83,
    category: "room",
    sizeMeters: [2.25, 0.86, 1.02],
  },
  room_l1_img2_maintenance_privacy_screen: {
    modelKey: "room_l1_img2_maintenance_privacy_screen",
    url: glbUrl84,
    category: "room",
    sizeMeters: [1.87, 1.574, 0.48],
  },
  room_l1_img2_mobile_repair_cart: {
    modelKey: "room_l1_img2_mobile_repair_cart",
    url: glbUrl85,
    category: "room",
    sizeMeters: [1.12, 0.98, 0.72],
  },
  room_l1_img2_overhead_rail_gantry: {
    modelKey: "room_l1_img2_overhead_rail_gantry",
    url: glbUrl86,
    category: "room",
    sizeMeters: [2.25, 2.13, 0.864],
  },
  room_l1_img2_parts_cabinet: {
    modelKey: "room_l1_img2_parts_cabinet",
    url: glbUrl87,
    category: "room",
    sizeMeters: [1.246, 1.7, 0.593],
  },
  room_l1_img2_parts_tote_stack: {
    modelKey: "room_l1_img2_parts_tote_stack",
    url: glbUrl88,
    category: "room",
    sizeMeters: [1.395, 1.168, 0.645],
  },
  room_l1_img2_prosthetic_parts_cabinet: {
    modelKey: "room_l1_img2_prosthetic_parts_cabinet",
    url: glbUrl89,
    category: "room",
    sizeMeters: [1.36, 1.62, 0.58],
  },
  room_l1_img2_repair_workbench: {
    modelKey: "room_l1_img2_repair_workbench",
    url: glbUrl90,
    category: "room",
    sizeMeters: [2, 1.25, 0.91],
  },
  room_l1_img2_robot_docking_post: {
    modelKey: "room_l1_img2_robot_docking_post",
    url: glbUrl91,
    category: "room",
    sizeMeters: [0.94, 1.53, 0.852],
  },
  room_l1_img2_service_stool: {
    modelKey: "room_l1_img2_service_stool",
    url: glbUrl92,
    category: "room",
    sizeMeters: [0.569, 0.605, 0.525],
  },
  room_l1_img2_sterile_tool_rack: {
    modelKey: "room_l1_img2_sterile_tool_rack",
    url: glbUrl93,
    category: "room",
    sizeMeters: [1.07, 1.84, 0.451],
  },
  room_l1_img2_sterile_wash_basin: {
    modelKey: "room_l1_img2_sterile_wash_basin",
    url: glbUrl94,
    category: "room",
    sizeMeters: [1.45, 1.02, 0.62],
  },
  room_l1_img2_utility_crate: {
    modelKey: "room_l1_img2_utility_crate",
    url: glbUrl95,
    category: "room",
    sizeMeters: [0.889, 0.79, 0.765],
  },
  room_l1_img2_valve_manifold_wall: {
    modelKey: "room_l1_img2_valve_manifold_wall",
    url: glbUrl96,
    category: "room",
    sizeMeters: [1.75, 1.22, 0.202],
  },
  room_l1_img2_wall_tool_board: {
    modelKey: "room_l1_img2_wall_tool_board",
    url: glbUrl97,
    category: "room",
    sizeMeters: [1.62, 1.02, 0.12],
  },
  room_l1_img2_warning_barrier: {
    modelKey: "room_l1_img2_warning_barrier",
    url: glbUrl98,
    category: "room",
    sizeMeters: [2.12, 1.1, 0.49],
  },
  room_l2_img2_camera_lamp: {
    modelKey: "room_l2_img2_camera_lamp",
    url: glbUrl99,
    category: "room",
    sizeMeters: [0.44, 1.63, 0.447],
  },
  room_l2_img2_carekeeper_armchair: {
    modelKey: "room_l2_img2_carekeeper_armchair",
    url: glbUrl100,
    category: "room",
    sizeMeters: [1.24, 1.111, 0.827],
  },
  room_l2_img2_family_portrait_console: {
    modelKey: "room_l2_img2_family_portrait_console",
    url: glbUrl101,
    category: "room",
    sizeMeters: [1.34, 0.92, 0.225],
  },
  room_l2_img2_living_end_elevator_fixture: {
    modelKey: "room_l2_img2_living_end_elevator_fixture",
    url: glbUrl102,
    category: "room",
    sizeMeters: [1.378, 2.12, 0.283],
  },
  room_l2_img2_modular_sofa: {
    modelKey: "room_l2_img2_modular_sofa",
    url: glbUrl103,
    category: "room",
    sizeMeters: [2.53, 1.007, 0.875],
  },
  room_l2_img2_nursery_bed: {
    modelKey: "room_l2_img2_nursery_bed",
    url: glbUrl104,
    category: "room",
    sizeMeters: [1.48, 0.85, 0.76],
  },
  room_l2_img2_observation_bookshelf: {
    modelKey: "room_l2_img2_observation_bookshelf",
    url: glbUrl105,
    category: "room",
    sizeMeters: [1.253, 1.837, 0.516],
  },
  room_l2_img2_observation_dining_table: {
    modelKey: "room_l2_img2_observation_dining_table",
    url: glbUrl106,
    category: "room",
    sizeMeters: [1.895, 0.727, 0.957],
  },
  room_l2_img2_scanner_wardrobe: {
    modelKey: "room_l2_img2_scanner_wardrobe",
    url: glbUrl107,
    category: "room",
    sizeMeters: [1.24, 2.005, 0.692],
  },
  room_l2_img2_service_kitchen_counter: {
    modelKey: "room_l2_img2_service_kitchen_counter",
    url: glbUrl108,
    category: "room",
    sizeMeters: [1.94, 1.065, 0.75],
  },
  room_l3_img2_archive_card_cabinet: {
    modelKey: "room_l3_img2_archive_card_cabinet",
    url: glbUrl109,
    category: "room",
    sizeMeters: [1.1, 1.47, 0.5],
  },
  room_l3_img2_display_plinth: {
    modelKey: "room_l3_img2_display_plinth",
    url: glbUrl110,
    category: "room",
    sizeMeters: [0.9, 1.475, 0.9],
  },
  room_l3_img2_evidence_round_table: {
    modelKey: "room_l3_img2_evidence_round_table",
    url: glbUrl111,
    category: "room",
    sizeMeters: [1.04, 0.77, 1.04],
  },
  room_l3_img2_label_terminal: {
    modelKey: "room_l3_img2_label_terminal",
    url: glbUrl112,
    category: "room",
    sizeMeters: [0.52, 1.27, 0.52],
  },
  room_l3_img2_mural_lightbox: {
    modelKey: "room_l3_img2_mural_lightbox",
    url: glbUrl113,
    category: "room",
    sizeMeters: [1.62, 1.1, 0.264],
  },
  room_l3_img2_preservation_case: {
    modelKey: "room_l3_img2_preservation_case",
    url: glbUrl114,
    category: "room",
    sizeMeters: [0.88, 1.755, 0.88],
  },
  room_l3_img2_queue_rail: {
    modelKey: "room_l3_img2_queue_rail",
    url: glbUrl115,
    category: "room",
    sizeMeters: [1.66, 0.995, 0.26],
  },
  room_l3_img2_specimen_bench: {
    modelKey: "room_l3_img2_specimen_bench",
    url: glbUrl116,
    category: "room",
    sizeMeters: [1.74, 0.74, 0.56],
  },
  room_l5_img2_archive_server_column: {
    modelKey: "room_l5_img2_archive_server_column",
    url: glbUrl117,
    category: "room",
    sizeMeters: [0.83, 2.2, 0.8],
  },
  room_l5_img2_biometric_filing_throne: {
    modelKey: "room_l5_img2_biometric_filing_throne",
    url: glbUrl118,
    category: "room",
    sizeMeters: [1.18, 1.56, 1.15],
  },
  room_l5_img2_core_memory_altar: {
    modelKey: "room_l5_img2_core_memory_altar",
    url: glbUrl119,
    category: "room",
    sizeMeters: [1.3, 1.31, 1.3],
  },
  room_l5_img2_data_spine_rack: {
    modelKey: "room_l5_img2_data_spine_rack",
    url: glbUrl120,
    category: "room",
    sizeMeters: [1, 2, 0.705],
  },
  room_l5_img2_heavy_archive_elevator_door: {
    modelKey: "room_l5_img2_heavy_archive_elevator_door",
    url: glbUrl121,
    category: "room",
    sizeMeters: [2.24, 2.64, 0.452],
  },
  room_l5_img2_identity_capsule_cabinet: {
    modelKey: "room_l5_img2_identity_capsule_cabinet",
    url: glbUrl122,
    category: "room",
    sizeMeters: [1.1, 2, 0.67],
  },
  room_l5_img2_lockbox_pedestal: {
    modelKey: "room_l5_img2_lockbox_pedestal",
    url: glbUrl123,
    category: "room",
    sizeMeters: [0.7, 1.015, 0.7],
  },
  room_l5_img2_retrieval_conveyor_table: {
    modelKey: "room_l5_img2_retrieval_conveyor_table",
    url: glbUrl124,
    category: "room",
    sizeMeters: [1.82, 0.727, 0.98],
  },
  room_l5_img2_route_key_pedestal: {
    modelKey: "room_l5_img2_route_key_pedestal",
    url: glbUrl125,
    category: "room",
    sizeMeters: [0.5, 1.125, 0.5],
  },
  room_l5_v3_anemone_lounge_chair: {
    modelKey: "room_l5_v3_anemone_lounge_chair",
    url: glbUrl126,
    category: "room",
    sizeMeters: [1.04, 1.133, 1.04],
  },
  room_l5_v3_bio_recline_couch: {
    modelKey: "room_l5_v3_bio_recline_couch",
    url: glbUrl127,
    category: "room",
    sizeMeters: [2.55, 0.667, 1.17],
  },
  room_l5_v3_cleaning_robot_dock: {
    modelKey: "room_l5_v3_cleaning_robot_dock",
    url: glbUrl128,
    category: "room",
    sizeMeters: [1.62, 0.445, 1.645],
  },
  room_l5_v3_core_route_map_table: {
    modelKey: "room_l5_v3_core_route_map_table",
    url: glbUrl129,
    category: "room",
    sizeMeters: [2, 0.988, 1.65],
  },
  room_l5_v3_corner_privacy_screen: {
    modelKey: "room_l5_v3_corner_privacy_screen",
    url: glbUrl130,
    category: "room",
    sizeMeters: [2.149, 2.005, 0.415],
  },
  room_l5_v3_crescent_low_sofa: {
    modelKey: "room_l5_v3_crescent_low_sofa",
    url: glbUrl131,
    category: "room",
    sizeMeters: [2.384, 0.72, 1.153],
  },
  room_l5_v3_curved_archive_shelf: {
    modelKey: "room_l5_v3_curved_archive_shelf",
    url: glbUrl132,
    category: "room",
    sizeMeters: [1.822, 2.08, 0.595],
  },
  room_l5_v3_evidence_coffee_table: {
    modelKey: "room_l5_v3_evidence_coffee_table",
    url: glbUrl133,
    category: "room",
    sizeMeters: [1.74, 0.66, 0.98],
  },
  room_l5_v3_hanging_cable_organizer: {
    modelKey: "room_l5_v3_hanging_cable_organizer",
    url: glbUrl134,
    category: "room",
    sizeMeters: [1.56, 1.195, 0.551],
  },
  room_l5_v3_human_archive_cabinet: {
    modelKey: "room_l5_v3_human_archive_cabinet",
    url: glbUrl135,
    category: "room",
    sizeMeters: [1.26, 1.845, 0.75],
  },
  room_l5_v3_intake_identity_gate: {
    modelKey: "room_l5_v3_intake_identity_gate",
    url: glbUrl136,
    category: "room",
    sizeMeters: [2.98, 2.58, 0.328],
  },
  room_l5_v3_limb_calibration_rack: {
    modelKey: "room_l5_v3_limb_calibration_rack",
    url: glbUrl137,
    category: "room",
    sizeMeters: [1.52, 2.28, 0.545],
  },
  room_l5_v3_memory_diagnostic_terminal: {
    modelKey: "room_l5_v3_memory_diagnostic_terminal",
    url: glbUrl138,
    category: "room",
    sizeMeters: [1.24, 2.16, 0.579],
  },
  room_l5_v3_reclamation_core_altar: {
    modelKey: "room_l5_v3_reclamation_core_altar",
    url: glbUrl139,
    category: "room",
    sizeMeters: [1.56, 1.232, 1.56],
  },
  room_l5_v3_release_key_vault: {
    modelKey: "room_l5_v3_release_key_vault",
    url: glbUrl140,
    category: "room",
    sizeMeters: [1.82, 1.735, 0.69],
  },
  room_l5_v3_service_side_console: {
    modelKey: "room_l5_v3_service_side_console",
    url: glbUrl141,
    category: "room",
    sizeMeters: [1.6, 1, 0.588],
  },
  room_l5_v3_specimen_drawer_stack: {
    modelKey: "room_l5_v3_specimen_drawer_stack",
    url: glbUrl142,
    category: "room",
    sizeMeters: [1.015, 2.05, 0.6],
  },
  room_l5_v3_surgical_light_stand: {
    modelKey: "room_l5_v3_surgical_light_stand",
    url: glbUrl143,
    category: "room",
    sizeMeters: [1.438, 2.692, 0.864],
  },
  room_l5_v3_three_lock_monolith: {
    modelKey: "room_l5_v3_three_lock_monolith",
    url: glbUrl144,
    category: "room",
    sizeMeters: [1.689, 2.28, 0.448],
  },
  room_l5_v3_tissue_freezer_cabinet: {
    modelKey: "room_l5_v3_tissue_freezer_cabinet",
    url: glbUrl145,
    category: "room",
    sizeMeters: [1.377, 1.755, 0.722],
  },
  room_l5_v4_ceiling_cable_tray: {
    modelKey: "room_l5_v4_ceiling_cable_tray",
    url: glbUrl146,
    category: "room",
    sizeMeters: [2.24, 0.297, 0.432],
  },
  room_l5_v4_ceiling_service_lamp: {
    modelKey: "room_l5_v4_ceiling_service_lamp",
    url: glbUrl147,
    category: "room",
    sizeMeters: [1.76, 0.253, 0.365],
  },
  room_l5_v4_clamp_relay_column: {
    modelKey: "room_l5_v4_clamp_relay_column",
    url: glbUrl148,
    category: "room",
    sizeMeters: [0.835, 1.79, 0.706],
  },
  room_l5_v4_floor_cable_bridge: {
    modelKey: "room_l5_v4_floor_cable_bridge",
    url: glbUrl149,
    category: "room",
    sizeMeters: [1.84, 0.205, 0.515],
  },
  room_l5_v4_maintenance_crate_stack: {
    modelKey: "room_l5_v4_maintenance_crate_stack",
    url: glbUrl150,
    category: "room",
    sizeMeters: [1.09, 0.82, 0.766],
  },
  room_l5_v4_sample_canister_rack: {
    modelKey: "room_l5_v4_sample_canister_rack",
    url: glbUrl151,
    category: "room",
    sizeMeters: [1.21, 1.72, 0.463],
  },
  room_l5_v4_wall_pipe_manifold: {
    modelKey: "room_l5_v4_wall_pipe_manifold",
    url: glbUrl152,
    category: "room",
    sizeMeters: [1.62, 1.08, 0.267],
  },
  room_l5_v4_warning_beacon_pylon: {
    modelKey: "room_l5_v4_warning_beacon_pylon",
    url: glbUrl153,
    category: "room",
    sizeMeters: [0.56, 1.16, 0.56],
  },
  room_rm_clinic_diagnosis_terminal: {
    modelKey: "room_rm_clinic_diagnosis_terminal",
    url: glbUrl154,
    category: "room",
    sizeMeters: [1.1, 1.411, 0.9],
  },
  room_rm_clinic_dosage_cart: {
    modelKey: "room_rm_clinic_dosage_cart",
    url: glbUrl155,
    category: "room",
    sizeMeters: [0.9, 1.1, 0.8],
  },
  room_rm_clinic_eye_lightbox: {
    modelKey: "room_rm_clinic_eye_lightbox",
    url: glbUrl156,
    category: "room",
    sizeMeters: [0.62, 0.88, 0.097],
  },
  room_rm_clinic_memory_projector: {
    modelKey: "room_rm_clinic_memory_projector",
    url: glbUrl157,
    category: "room",
    sizeMeters: [1, 1.448, 1.713],
  },
  room_rm_clinic_sedation_gate: {
    modelKey: "room_rm_clinic_sedation_gate",
    url: glbUrl158,
    category: "room",
    sizeMeters: [1.8, 2.43, 0.8],
  },
  room_rm_clinic_surgical_curtain: {
    modelKey: "room_rm_clinic_surgical_curtain",
    url: glbUrl159,
    category: "room",
    sizeMeters: [1.9, 2.055, 1.1],
  },
  room_rm_clinic_therapy_chair: {
    modelKey: "room_rm_clinic_therapy_chair",
    url: glbUrl160,
    category: "room",
    sizeMeters: [1.4, 1.592, 1.894],
  },
  room_rm_clinic_waiting_row: {
    modelKey: "room_rm_clinic_waiting_row",
    url: glbUrl161,
    category: "room",
    sizeMeters: [2.1, 0.942, 0.9],
  },
  room_rm_core_arena_marker: {
    modelKey: "room_rm_core_arena_marker",
    url: glbUrl162,
    category: "room",
    sizeMeters: [1.98, 0.068, 1.98],
  },
  room_rm_core_conveyor_segment: {
    modelKey: "room_rm_core_conveyor_segment",
    url: glbUrl163,
    category: "room",
    sizeMeters: [2.3, 0.93, 1],
  },
  room_rm_core_coolant_manifold: {
    modelKey: "room_rm_core_coolant_manifold",
    url: glbUrl164,
    category: "room",
    sizeMeters: [1.9, 1.41, 1],
  },
  room_rm_core_final_lock_column: {
    modelKey: "room_rm_core_final_lock_column",
    url: glbUrl165,
    category: "room",
    sizeMeters: [1.2, 2.72, 1.2],
  },
  room_rm_core_identity_server: {
    modelKey: "room_rm_core_identity_server",
    url: glbUrl166,
    category: "room",
    sizeMeters: [1.1, 2.2, 0.9],
  },
  room_rm_core_incinerator_hatch: {
    modelKey: "room_rm_core_incinerator_hatch",
    url: glbUrl167,
    category: "room",
    sizeMeters: [1.68, 0.17, 1.68],
  },
  room_rm_core_reclamation_altar: {
    modelKey: "room_rm_core_reclamation_altar",
    url: glbUrl168,
    category: "room",
    sizeMeters: [2.4, 1.114, 2.4],
  },
  room_rm_core_warning_pylon: {
    modelKey: "room_rm_core_warning_pylon",
    url: glbUrl169,
    category: "room",
    sizeMeters: [0.7, 1.88, 0.7],
  },
  room_rm_home_crib_monitor: {
    modelKey: "room_rm_home_crib_monitor",
    url: glbUrl170,
    category: "room",
    sizeMeters: [1.784, 1.504, 1.1],
  },
  room_rm_home_family_table: {
    modelKey: "room_rm_home_family_table",
    url: glbUrl171,
    category: "room",
    sizeMeters: [2.35, 0.97, 2.439],
  },
  room_rm_home_intercom_panel: {
    modelKey: "room_rm_home_intercom_panel",
    url: glbUrl172,
    category: "room",
    sizeMeters: [0.4, 0.62, 0.09],
  },
  room_rm_home_kitchen_fake: {
    modelKey: "room_rm_home_kitchen_fake",
    url: glbUrl173,
    category: "room",
    sizeMeters: [1.9, 1.11, 1],
  },
  room_rm_home_observation_sofa: {
    modelKey: "room_rm_home_observation_sofa",
    url: glbUrl174,
    category: "room",
    sizeMeters: [2.3, 1.095, 1.2],
  },
  room_rm_home_photo_cluster: {
    modelKey: "room_rm_home_photo_cluster",
    url: glbUrl175,
    category: "room",
    sizeMeters: [1.8, 1.002, 0.085],
  },
  room_rm_home_tv_shrine_broken: {
    modelKey: "room_rm_home_tv_shrine_broken",
    url: glbUrl176,
    category: "room",
    sizeMeters: [1.9, 1.725, 0.9],
  },
  room_rm_home_wall_rupture: {
    modelKey: "room_rm_home_wall_rupture",
    url: glbUrl177,
    category: "room",
    sizeMeters: [1.7, 1.5, 0.14],
  },
  room_rm_maint_battery_rack: {
    modelKey: "room_rm_maint_battery_rack",
    url: glbUrl178,
    category: "room",
    sizeMeters: [1.1, 1.56, 0.7],
  },
  room_rm_maint_broken_cradle: {
    modelKey: "room_rm_maint_broken_cradle",
    url: glbUrl179,
    category: "room",
    sizeMeters: [2.4, 0.919, 2.1],
  },
  room_rm_maint_cable_spine: {
    modelKey: "room_rm_maint_cable_spine",
    url: glbUrl180,
    category: "room",
    sizeMeters: [2.6, 0.33, 0.974],
  },
  room_rm_maint_coolant_drums: {
    modelKey: "room_rm_maint_coolant_drums",
    url: glbUrl181,
    category: "room",
    sizeMeters: [1.593, 1.12, 1.487],
  },
  room_rm_maint_door_console: {
    modelKey: "room_rm_maint_door_console",
    url: glbUrl182,
    category: "room",
    sizeMeters: [1.2, 1.37, 0.9],
  },
  room_rm_maint_gantry_hoist: {
    modelKey: "room_rm_maint_gantry_hoist",
    url: glbUrl183,
    category: "room",
    sizeMeters: [1.759, 2.05, 1.1],
  },
  room_rm_maint_tool_wall: {
    modelKey: "room_rm_maint_tool_wall",
    url: glbUrl184,
    category: "room",
    sizeMeters: [1.88, 1.245, 0.13],
  },
  room_rm_maint_weapon_cradle: {
    modelKey: "room_rm_maint_weapon_cradle",
    url: glbUrl185,
    category: "room",
    sizeMeters: [1.3, 0.87, 0.9],
  },
  room_rm_museum_archive_plinth: {
    modelKey: "room_rm_museum_archive_plinth",
    url: glbUrl186,
    category: "room",
    sizeMeters: [0.9, 1.199, 0.9],
  },
  room_rm_museum_audio_stand: {
    modelKey: "room_rm_museum_audio_stand",
    url: glbUrl187,
    category: "room",
    sizeMeters: [0.7, 1.689, 0.7],
  },
  room_rm_museum_body_display: {
    modelKey: "room_rm_museum_body_display",
    url: glbUrl188,
    category: "room",
    sizeMeters: [1.28, 1.76, 0.108],
  },
  room_rm_museum_curator_desk: {
    modelKey: "room_rm_museum_curator_desk",
    url: glbUrl189,
    category: "room",
    sizeMeters: [1.9, 1.253, 1.2],
  },
  room_rm_museum_restoration_bench: {
    modelKey: "room_rm_museum_restoration_bench",
    url: glbUrl190,
    category: "room",
    sizeMeters: [1.8, 1.296, 1.1],
  },
  room_rm_museum_route_inlay: {
    modelKey: "room_rm_museum_route_inlay",
    url: glbUrl191,
    category: "room",
    sizeMeters: [2, 0.057, 0.5],
  },
  room_rm_museum_specimen_case: {
    modelKey: "room_rm_museum_specimen_case",
    url: glbUrl192,
    category: "room",
    sizeMeters: [1.1, 1.98, 1.1],
  },
  room_rm_museum_stanchion: {
    modelKey: "room_rm_museum_stanchion",
    url: glbUrl193,
    category: "room",
    sizeMeters: [1.67, 1.02, 0.5],
  },
} as const satisfies EnvironmentModelRegistry;
