import type { LevelMapConfig } from "../../schema/levelConfig";

export const level05Map: LevelMapConfig = {
  id: "level_05_reclamation_core_map",
  schemaVersion: "hp.map.v1",
  presentation: {
    archetype: "boss_chamber",
    shellKit: "hp:reclamation_core_shell_v1",
    lightingPreset: "hp:reclamation_core_v1",
    overrides: {
      propDensity: "sparse",
      floorWear: 0.34,
      ceilingLightIntensity: 0.92,
      doorStateStyle: "core_amber_to_red",
      fogFar: 96,
    },
  },
  rooms: [
    {
      id: "level_05_core_entry",
      label: "回收核心入口",
      bounds: { center: [0, 0, 17], size: [10, 4.2, 7] },
      mood: "uneasy",
      skinKey: "maintenance_service",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.48,
      entryDialogueTrigger: "level_start",
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ffd36d" },
      aesthetic: { style: "hazard", detail: "medium", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_lock_hub",
      label: "回收中庭",
      bounds: { center: [0, 0, 7.5], size: [18, 4.8, 12] },
      mood: "reveal",
      skinKey: "reclamation_core_chamber",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.7,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ffd36d" },
      aesthetic: { style: "hazard", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_north_lock",
      label: "北侧制动间",
      bounds: { center: [0, 0, -2.25], size: [9, 4.6, 7.5] },
      mood: "quiet",
      skinKey: "reclamation_core_chamber",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.66,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#7ff2ff" },
      aesthetic: { style: "hazard", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_east_lock",
      label: "东侧供能间",
      bounds: { center: [13, 0, 7.5], size: [8, 4.6, 8] },
      mood: "combat",
      skinKey: "maintenance_service",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.72,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#9ff3ff" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_west_lock",
      label: "西侧回收间",
      bounds: { center: [-13, 0, 7.5], size: [8, 4.6, 8] },
      mood: "combat",
      skinKey: "reclamation_core_chamber",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.8,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ff6a52" },
      aesthetic: { style: "hazard", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_platform",
      label: "回收内台",
      bounds: { center: [0, 0, -12], size: [16, 5, 13] },
      mood: "boss",
      skinKey: "reclamation_core_chamber",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.92,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ff5b4c" },
      aesthetic: { style: "hazard", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_archive_room",
      label: "实验档案室",
      bounds: { center: [11.5, 0, -12], size: [7, 4.5, 7] },
      mood: "quiet",
      skinKey: "memory_clinic_sterile",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.62,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#eafcff" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_05_identity_file",
      label: "归档电梯间",
      bounds: { center: [0, 0, -22], size: [9, 4.6, 7] },
      mood: "reveal",
      skinKey: "service_exit_red",
      floorMaterialKey: "red_exit_floor",
      wallMaterialKey: "red_exit_wall",
      ambientPressure: 0.86,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#fff3df" },
      aesthetic: { style: "exit", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
  ],
  doors: [
    {
      id: "level_05_hub_door",
      label: "回收中庭闸门",
      fromRoomId: "level_05_core_entry",
      toRoomId: "level_05_lock_hub",
      position: [0, 0, 13.5],
      size: [4.2, 3.1, 0.42],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "回收中庭闸门已打开。" },
      visualKey: "reclamation_archive_door",
      materialKey: "reclamation_core_wall",
      panelPosition: [2.7, 0, 13.86],
      openSpeed: 1.18,
      cameraImpact: { shake: 0.2, fovKick: 1.2 },
    },
    {
      id: "level_05_north_door",
      label: "北制动门",
      fromRoomId: "level_05_lock_hub",
      toRoomId: "level_05_north_lock",
      position: [0, 0, 1.5],
      size: [3.1, 2.85, 0.36],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "北制动门已打开。" },
      visualKey: "reclamation_archive_door",
      materialKey: "reclamation_core_wall",
      panelPosition: [2.1, 0, 1.86],
      openSpeed: 1.08,
    },
    {
      id: "level_05_east_door",
      label: "东供能门",
      fromRoomId: "level_05_lock_hub",
      toRoomId: "level_05_east_lock",
      position: [9, 0, 7.5],
      size: [2.8, 2.75, 0.34],
      yaw: Math.PI / 2,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "东供能门已打开。" },
      visualKey: "reclamation_archive_door",
      materialKey: "reclamation_core_wall",
      panelPosition: [8.64, 0, 9.25],
      openSpeed: 1.08,
    },
    {
      id: "level_05_west_door",
      label: "西回收门",
      fromRoomId: "level_05_lock_hub",
      toRoomId: "level_05_west_lock",
      position: [-9, 0, 7.5],
      size: [2.8, 2.75, 0.34],
      yaw: Math.PI / 2,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "西回收门已打开。" },
      visualKey: "reclamation_archive_door",
      materialKey: "reclamation_core_wall",
      panelPosition: [-8.64, 0, 5.75],
      openSpeed: 1.08,
    },
    {
      id: "level_05_platform_door",
      label: "回收内台闸门",
      fromRoomId: "level_05_north_lock",
      toRoomId: "level_05_platform",
      position: [0, 0, -5.5],
      size: [4.6, 3.2, 0.45],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "回收内台闸门已打开。" },
      visualKey: "reclamation_archive_door",
      materialKey: "terminal_red",
      panelPosition: [3, 0, -5.14],
      openSpeed: 1.22,
      cameraImpact: { shake: 0.28, fovKick: 1.4 },
    },
    {
      id: "level_05_archive_door",
      label: "实验档案室门",
      fromRoomId: "level_05_platform",
      toRoomId: "level_05_archive_room",
      position: [8, 0, -12],
      size: [2.6, 2.65, 0.32],
      yaw: Math.PI / 2,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "实验档案室门已打开。" },
      visualKey: "clinic_memory_door",
      materialKey: "memory_clinic_wall",
      panelPosition: [7.64, 0, -10.25],
      openSpeed: 1.05,
    },
    {
      id: "level_05_identity_door",
      label: "归档电梯门",
      fromRoomId: "level_05_platform",
      toRoomId: "level_05_identity_file",
      position: [0, 0, -18.5],
      size: [4.8, 3.3, 0.46],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "归档电梯门已打开。" },
      visualKey: "service_elevator_door",
      materialKey: "service_elevator_metal",
      panelPosition: [3.05, 0, -18.14],
      openSpeed: 1.28,
      cameraImpact: { shake: 0.42, fovKick: 2.2, rumble: 0.18, rumbleDuration: 0.24 },
    },
  ],
  keyItems: [],
  interactions: [
    {
      id: "level_05_identity_interaction",
      type: "exit",
      roomId: "level_05_identity_file",
      position: [0, 0, -23.9],
      radius: 2.1,
      visualKey: "service_elevator_panel",
      materialKey: "terminal_cyan",
      label: "进入归档电梯",
      opensDoorId: "level_05_identity_door",
    },
  ],
  pickups: [],
  props: [],
  navigation: {
    criticalPathRoomIds: [
      "level_05_core_entry",
      "level_05_lock_hub",
      "level_05_north_lock",
      "level_05_platform",
      "level_05_identity_file",
    ],
    optionalRoomIds: ["level_05_east_lock", "level_05_west_lock", "level_05_archive_room"],
    maxBacktrackSeconds: 42,
    mobileReadableDoorCount: 7,
  },
};
