import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const bigScreenFormulaSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_big_screen_formula_combo",
  title: "大屏 + 颜色球 + 公式密码 Smoke",
  spawnPoint: [0, 0, 6.2],
  initialInventory: {
    hasRod: true,
    hasPistol: true,
    equipWeapon: "pulseRifle",
  },
  initialWaveStartDelay: 0,
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "screen_combo_exit",
    position: [0, 0, -11.8],
    radius: 1.85,
    unlockMessage: "公式门禁接受了大屏线索。",
    unlockWarning: { label: "出口已通电", detail: "颜色顺序和公式密码都正确" },
    transitionMessage: "Smoke 电梯下行：大屏组合 puzzle config 可通关。",
    victoryMessage: "Smoke 完成：大屏状态、打球联动和公式密码锁全部由 config 驱动。",
  },
  pickups: {
    ...level01MaintenanceBay.pickups,
    storyPickups: [],
  },
  map: {
    id: "smoke_big_screen_formula_combo_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "screen_combo_entry",
        label: "屏幕观察间",
        bounds: { center: [0, 0, 6], size: [8, 4, 5.5] },
        mood: "uneasy",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
        aesthetic: { style: "sterile", detail: "high" },
      },
      {
        id: "screen_combo_orbs",
        label: "颜色反应间",
        bounds: { center: [0, 0, 0], size: [8, 4, 6] },
        mood: "quiet",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#f7c65c" },
        aesthetic: { style: "hazard", detail: "high" },
      },
      {
        id: "screen_combo_formula",
        label: "公式门禁间",
        bounds: { center: [0, 0, -6.6], size: [8, 4, 5.8] },
        mood: "uneasy",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
        aesthetic: { style: "maintenance", detail: "high" },
      },
      {
        id: "screen_combo_exit_room",
        label: "组合出口",
        bounds: { center: [0, 0, -11.8], size: [5.4, 4, 4.2] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
        aesthetic: { style: "exit", detail: "medium" },
      },
    ],
    doors: [
      {
        id: "screen_combo_entry_door",
        label: "观察间门",
        fromRoomId: "screen_combo_entry",
        toRoomId: "screen_combo_orbs",
        position: [0, 0, 3],
        size: [3.1, 3.1, 0.35],
        yaw: 0,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
      },
      {
        id: "screen_combo_orb_door",
        label: "反应间门",
        fromRoomId: "screen_combo_orbs",
        toRoomId: "screen_combo_formula",
        position: [0, 0, -3.25],
        size: [3.1, 3.1, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "screen_combo_orb_sequence",
          lockedMessage: "颜色反应还没按顺序完成。",
          unlockedMessage: "反应间门已打开。",
        },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
        panelPosition: [1.82, 0, -2.9],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.22, fovKick: 1.2 },
      },
      {
        id: "screen_combo_formula_door",
        label: "公式门禁",
        fromRoomId: "screen_combo_formula",
        toRoomId: "screen_combo_exit_room",
        position: [0, 0, -9.6],
        size: [3.1, 3.1, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "screen_combo_formula_code",
          lockedMessage: "公式门禁还在等待结果。",
          unlockedMessage: "公式门禁已打开。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.82, 0, -9.25],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.28, fovKick: 1.35 },
      },
    ],
    keyItems: [],
    interactions: [
      {
        id: "screen_combo_color_screen_panel",
        type: "big_screen",
        roomId: "screen_combo_entry",
        position: [0, 0, 3.35],
        radius: 2.05,
        visualKey: "terminal_puzzle_big_screen",
        materialKey: "terminal_cyan",
        label: "观察屏",
      },
      {
        id: "screen_combo_formula_screen_panel",
        type: "big_screen",
        roomId: "screen_combo_formula",
        position: [-2.35, 0, -9.35],
        radius: 1.95,
        visualKey: "terminal_puzzle_big_screen",
        materialKey: "terminal_cyan",
        label: "公式屏",
      },
      {
        id: "screen_combo_keypad",
        type: "door_panel",
        roomId: "screen_combo_formula",
        position: [2.35, 0, -9.35],
        radius: 1.75,
        visualKey: "direction_keypad_panel",
        materialKey: "terminal_cyan",
        label: "公式门禁面板",
      },
      {
        id: "use_screen_combo_exit",
        type: "exit",
        roomId: "screen_combo_exit_room",
        position: [0, 0, -11.8],
        radius: 1.85,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入测试出口",
        requiresObjectiveId: "input_screen_combo_formula_code",
      },
    ],
    navigation: {
      criticalPathRoomIds: ["screen_combo_entry", "screen_combo_orbs", "screen_combo_formula", "screen_combo_exit_room"],
      optionalRoomIds: [],
      maxBacktrackSeconds: 18,
      mobileReadableDoorCount: 3,
    },
  },
  puzzles: [
    {
      id: "screen_combo_orb_sequence",
      type: "hit_sequence",
      label: "屏幕颜色顺序",
      roomId: "screen_combo_orbs",
      targets: [
        { id: "screen_combo_yellow_orb", label: "黄球", roomId: "screen_combo_orbs", colorKey: "yellow", position: [-2.1, 1.05, 0.25], radius: 0.58, visualKey: "puzzle_orb_yellow", materialKey: "puzzle_yellow_glass" },
        { id: "screen_combo_red_orb", label: "红球", roomId: "screen_combo_orbs", colorKey: "red", position: [0, 1.05, -0.4], radius: 0.58, visualKey: "puzzle_orb_red", materialKey: "puzzle_red_glass" },
        { id: "screen_combo_blue_orb", label: "蓝球", roomId: "screen_combo_orbs", colorKey: "blue", position: [2.1, 1.05, 0.25], radius: 0.58, visualKey: "puzzle_orb_blue", materialKey: "puzzle_blue_glass" },
      ],
      clue: {
        type: "pattern_panel",
        label: "观察屏顺序",
        roomId: "screen_combo_entry",
        interactionId: "screen_combo_color_screen_panel",
        sequence: ["screen_combo_yellow_orb", "screen_combo_red_orb", "screen_combo_blue_orb"],
        roomEnterDetail: "观察屏给出了颜色顺序。",
        surfaces: [
          {
            id: "screen_combo_floor_color_strip",
            roomId: "screen_combo_entry",
            surface: "floor",
            position: [0, 0.08, 5.2],
            size: [3.4, 0.72],
            yaw: 0,
            sequence: ["screen_combo_yellow_orb", "screen_combo_red_orb", "screen_combo_blue_orb"],
            label: "屏幕顺序",
          },
        ],
      },
      input: {
        method: "weapon_hit",
        allowedWeapons: ["pulseRifle"],
        resetOnMistake: true,
        showProgressPulse: true,
      },
      fail: {
        message: "颜色顺序被清空。",
        cameraImpact: { shake: 0.2, fovKick: 0.8 },
      },
      success: {
        opensDoorId: "screen_combo_orb_door",
        completesObjectiveId: "solve_screen_combo_orbs",
        dialogueTrigger: "screen_combo_orbs_done",
        rewardPulse: { label: "反应门开启", detail: "公式屏收到电源", rarity: "rare" },
        rewardPulseDuration: 1.35,
        cameraImpact: { shake: 0.24, fovKick: 1.2, rumble: 0.18, rumbleDuration: 0.18 },
        audio: { key: "system_exit_open", intensity: 0.72 },
        actions: [{ type: "set_big_screen_state", screenId: "screen_combo_formula_screen", stateId: "formula_hint" }],
      },
    },
    {
      id: "screen_combo_formula_code",
      type: "code_lock",
      label: "公式门禁",
      roomId: "screen_combo_formula",
      interactionId: "screen_combo_keypad",
      code: {
        source: "formula",
        formula: {
          expression: "12*3+4",
          answer: "040",
          display: "12 x 3 + 4",
          hint: "门禁需要三位数。",
          padLength: 3,
        },
        hint: {
          source: "screen",
          label: "公式屏线索",
          detail: "把公式结果补成三位数。",
        },
      },
      input: {
        length: 3,
        mode: "digit_buttons",
        allowBackspace: true,
        clearOnMistake: false,
        submitLabel: "确认公式",
      },
      clues: [],
      fail: {
        message: "公式结果不匹配。",
        cameraImpact: { shake: 0.2, fovKick: 0.8 },
        audio: { key: "enemy_hit", intensity: 0.42 },
      },
      success: {
        opensDoorId: "screen_combo_formula_door",
        unlockExit: true,
        completesObjectiveId: "input_screen_combo_formula_code",
        rewardPulse: { label: "公式门禁解除", detail: "出口通电", rarity: "epic" },
        rewardPulseDuration: 1.55,
        cameraImpact: { shake: 0.32, fovKick: 1.55, rumble: 0.22, rumbleDuration: 0.2 },
        audio: { key: "system_exit_open", intensity: 0.92 },
      },
    },
  ],
  bigScreens: [
    {
      id: "screen_combo_color_screen",
      roomId: "screen_combo_entry",
      interactionId: "screen_combo_color_screen_panel",
      label: "观察屏",
      initialStateId: "off",
      activationStateId: "color_hint",
      oneShot: true,
      modelKey: "terminal_puzzle_big_screen",
      visualKey: "terminal_puzzle_big_screen",
      materialKey: "terminal_cyan",
      position: [0, 1.48, 3.35],
      yaw: Math.PI,
      size: [2.6, 1.36],
      states: [
        { id: "off", mode: "off", powered: false, label: "屏幕休眠" },
        {
          id: "color_hint",
          mode: "color_sequence",
          powered: true,
          title: "颜色顺序",
          colors: ["yellow", "red", "blue"],
          message: "观察屏亮起：黄、红、蓝。",
          rewardPulse: { label: "观察屏上线", detail: "颜色顺序已记录", rarity: "story" },
          rewardPulseDuration: 1.25,
          audio: { key: "ui_upgrade_select", intensity: 0.55 },
        },
      ],
    },
    {
      id: "screen_combo_formula_screen",
      roomId: "screen_combo_formula",
      interactionId: "screen_combo_formula_screen_panel",
      label: "公式屏",
      initialStateId: "off",
      activationStateId: "formula_hint",
      modelKey: "terminal_puzzle_big_screen",
      visualKey: "terminal_puzzle_big_screen",
      materialKey: "terminal_cyan",
      position: [-2.35, 1.48, -9.35],
      yaw: 0,
      size: [2.55, 1.34],
      states: [
        { id: "off", mode: "off", powered: false, label: "屏幕休眠" },
        {
          id: "formula_hint",
          mode: "formula",
          powered: true,
          title: "门禁公式",
          formula: {
            expression: "12*3+4",
            answer: "040",
            display: "12 x 3 + 4 = 40",
            hint: "补成三位：040",
            padLength: 3,
          },
          message: "公式屏亮起：门禁结果需要三位。",
          rewardPulse: { label: "公式屏上线", detail: "公式线索已暴露", rarity: "story" },
          rewardPulseDuration: 1.25,
          audio: { key: "system_exit_open", intensity: 0.45 },
        },
      ],
    },
  ],
  objectiveChain: [
    {
      id: "activate_screen_combo_color_screen",
      type: "custom",
      title: "读取观察屏",
      detail: "屏幕会给出颜色顺序。",
      requiredIds: ["screen_combo_color_screen:color_hint"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "big_screen_state", id: "screen_combo_color_screen", optionId: "color_hint" },
      nextObjectiveId: "solve_screen_combo_orbs",
      hudLabel: "观察屏",
      guidance: { targetType: "interaction", targetId: "screen_combo_color_screen_panel", label: "观察屏", detail: "靠近打开屏幕。", urgency: "puzzle" },
    },
    {
      id: "solve_screen_combo_orbs",
      type: "custom",
      title: "击中颜色球",
      detail: "按屏幕顺序攻击颜色球。",
      requiredIds: ["screen_combo_orb_sequence"],
      startsWhen: { type: "big_screen_state", id: "screen_combo_color_screen", optionId: "color_hint" },
      completesWhen: { type: "puzzle_completed", id: "screen_combo_orb_sequence" },
      nextObjectiveId: "input_screen_combo_formula_code",
      hudLabel: "颜色顺序",
      guidance: { targetType: "puzzle", targetId: "screen_combo_orb_sequence", label: "颜色球", detail: "按黄、红、蓝攻击。", urgency: "puzzle" },
    },
    {
      id: "input_screen_combo_formula_code",
      type: "custom",
      title: "输入公式门禁",
      detail: "公式屏给出结果。",
      requiredIds: ["screen_combo_formula_code", "screen_combo_formula_screen:formula_hint"],
      startsWhen: { type: "puzzle_completed", id: "screen_combo_orb_sequence" },
      completesWhen: { type: "puzzle_completed", id: "screen_combo_formula_code" },
      nextObjectiveId: "reach_screen_combo_exit",
      hudLabel: "公式门禁",
      guidance: { targetType: "interaction", targetId: "screen_combo_keypad", label: "公式门禁", detail: "输入三位结果。", urgency: "puzzle" },
    },
    {
      id: "reach_screen_combo_exit",
      type: "reach_exit",
      title: "进入组合出口",
      detail: "大屏组合链路已通过。",
      requiredIds: ["use_screen_combo_exit"],
      startsWhen: { type: "puzzle_completed", id: "screen_combo_formula_code" },
      completesWhen: { type: "interaction_completed", id: "use_screen_combo_exit" },
      hudLabel: "组合出口",
      guidance: { targetType: "interaction", targetId: "use_screen_combo_exit", label: "测试出口", detail: "进入出口。", urgency: "exit" },
    },
  ],
  waves: [],
  dialogues: [
    ...level01MaintenanceBay.dialogues,
    { id: "screen_combo_orbs_done_01", trigger: "screen_combo_orbs_done", speaker: "观察屏", line: "颜色顺序通过。公式屏已接入。", tone: "system", duration: 2.3 },
  ],
};

export const bigScreenFormulaSmokeValidationReport = validateLevelConfig(bigScreenFormulaSmokeLevel);
