import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const directionCodeSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_direction_code_lock",
  title: "方位密码锁 Smoke",
  spawnPoint: [0, 0, 1.6],
  initialWaveStartDelay: 0,
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "direction_code_exit",
    position: [0, 0, -13.2],
    radius: 1.8,
    unlockMessage: "最终门禁接受了方位密码。",
    unlockWarning: { label: "出口已通电", detail: "钥匙和方位密码都正确" },
    transitionMessage: "Smoke 电梯下行：方位密码锁已由 config 驱动。",
    victoryMessage: "Smoke 完成：东西南北数字、钥匙和密码锁全部由 config 驱动。",
  },
  pickups: {
    ...level01MaintenanceBay.pickups,
    storyPickups: [],
  },
  map: {
    id: "smoke_direction_code_lock_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "direction_hub",
        label: "方位大厅",
        bounds: { center: [0, 0, 0], size: [7, 4, 7] },
        mood: "uneasy",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "north_digit_room",
        label: "北侧标记室",
        bounds: { center: [0, 0, -7], size: [6, 4, 5] },
        mood: "quiet",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "east_digit_room",
        label: "东侧标记室",
        bounds: { center: [7, 0, 0], size: [5, 4, 6] },
        mood: "quiet",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#f7c65c" },
      },
      {
        id: "south_digit_room",
        label: "南侧标记室",
        bounds: { center: [0, 0, 7], size: [6, 4, 5] },
        mood: "quiet",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "west_key_room",
        label: "西侧钥匙室",
        bounds: { center: [-7, 0, 0], size: [5, 4, 6] },
        mood: "uneasy",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
      {
        id: "direction_exit_room",
        label: "最终出口",
        bounds: { center: [0, 0, -13.2], size: [5.4, 4, 4] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
    ],
    doors: [
      {
        id: "north_hub_door",
        label: "北侧门",
        fromRoomId: "direction_hub",
        toRoomId: "north_digit_room",
        position: [0, 0, -4],
        size: [2.8, 3, 0.32],
        yaw: 0,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
      },
      {
        id: "east_hub_door",
        label: "东侧门",
        fromRoomId: "direction_hub",
        toRoomId: "east_digit_room",
        position: [4, 0, 0],
        size: [2.8, 3, 0.32],
        yaw: Math.PI / 2,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
      },
      {
        id: "south_hub_door",
        label: "南侧门",
        fromRoomId: "direction_hub",
        toRoomId: "south_digit_room",
        position: [0, 0, 4],
        size: [2.8, 3, 0.32],
        yaw: 0,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
      },
      {
        id: "west_hub_door",
        label: "西侧门",
        fromRoomId: "direction_hub",
        toRoomId: "west_key_room",
        position: [-4, 0, 0],
        size: [2.8, 3, 0.32],
        yaw: Math.PI / 2,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
      },
      {
        id: "final_direction_door",
        label: "最终方位锁门",
        fromRoomId: "north_digit_room",
        toRoomId: "direction_exit_room",
        position: [0, 0, -10.35],
        size: [3.1, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "final_direction_code",
          keyItemId: "exit_key",
          lockedMessage: "需要出口钥匙和方位密码。",
          unlockedMessage: "最终方位锁已打开。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.85, 0, -10.02],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.24, fovKick: 1.3 },
      },
    ],
    keyItems: [
      {
        id: "exit_key",
        label: "出口钥匙",
        roomId: "west_key_room",
        position: [-7, 0, -1.1],
        collectRadius: 1.45,
        visualKey: "yellow_access_card",
        materialKey: "access_card_gold",
        requiredForDoorIds: ["final_direction_door"],
        rewardPulse: { label: "出口钥匙", detail: "最终门仍需要密码", rarity: "rare" },
      },
    ],
    interactions: [
      {
        id: "final_direction_keypad",
        type: "door_panel",
        roomId: "north_digit_room",
        position: [1.9, 0, -8.75],
        radius: 1.6,
        visualKey: "direction_keypad_panel",
        materialKey: "terminal_cyan",
        label: "方位密码面板",
      },
      {
        id: "use_direction_code_exit",
        type: "exit",
        roomId: "direction_exit_room",
        position: [0, 0, -13.2],
        radius: 1.8,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入测试出口",
        requiresObjectiveId: "unlock_final_direction_exit",
      },
    ],
    navigation: {
      criticalPathRoomIds: ["direction_hub", "west_key_room", "north_digit_room", "direction_exit_room"],
      optionalRoomIds: ["east_digit_room", "south_digit_room"],
      maxBacktrackSeconds: 22,
      mobileReadableDoorCount: 5,
    },
  },
  puzzles: [
    {
      id: "final_direction_code",
      type: "code_lock",
      label: "方位密码锁",
      roomId: "north_digit_room",
      interactionId: "final_direction_keypad",
      requiredKeyItemId: "exit_key",
      code: {
        source: "direction_room_digits",
        directionOrder: ["east", "west", "south", "north"],
      },
      input: {
        length: 4,
        mode: "digit_buttons",
        allowBackspace: true,
        clearOnMistake: false,
        submitLabel: "确认门禁",
      },
      clues: [
        {
          id: "north_digit",
          type: "number_decal",
          roomId: "north_digit_room",
          direction: "north",
          value: "7",
          visualKey: "wall_digit_warning",
          position: [0, 1.55, -8.85],
          yaw: 0,
          label: "北 7",
        },
        {
          id: "east_digit",
          type: "number_decal",
          roomId: "east_digit_room",
          direction: "east",
          value: "2",
          visualKey: "wall_digit_warning",
          position: [8.85, 1.55, 0],
          yaw: -Math.PI / 2,
          label: "东 2",
        },
        {
          id: "south_digit",
          type: "number_decal",
          roomId: "south_digit_room",
          direction: "south",
          value: "9",
          visualKey: "wall_digit_warning",
          position: [0, 1.55, 8.85],
          yaw: Math.PI,
          label: "南 9",
        },
        {
          id: "west_digit",
          type: "number_decal",
          roomId: "west_key_room",
          direction: "west",
          value: "4",
          visualKey: "wall_digit_warning",
          position: [-8.85, 1.55, 0],
          yaw: Math.PI / 2,
          label: "西 4",
        },
      ],
      fail: {
        message: "密码不对。方位顺序没有通过。",
        cameraImpact: { shake: 0.18, fovKick: 0.8 },
        audio: { key: "enemy_hit", intensity: 0.44 },
      },
      success: {
        opensDoorId: "final_direction_door",
        unlockExit: true,
        completesObjectiveId: "unlock_final_direction_exit",
        rewardPulse: { label: "方位锁解除", detail: "东-西-南-北密码确认", rarity: "epic" },
        rewardPulseDuration: 1.6,
        cameraImpact: { shake: 0.32, fovKick: 1.55, rumble: 0.24, rumbleDuration: 0.22 },
        audio: { key: "system_exit_open", intensity: 0.96 },
      },
    },
  ],
  objectiveChain: [
    {
      id: "find_exit_key",
      type: "collect_key",
      title: "找出口钥匙",
      detail: "西侧房间里有最终门钥匙。",
      requiredIds: ["exit_key"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "key_collected", id: "exit_key" },
      nextObjectiveId: "unlock_final_direction_exit",
      hudLabel: "出口钥匙",
    },
    {
      id: "unlock_final_direction_exit",
      type: "custom",
      title: "输入方位密码",
      detail: "按面板上的方位顺序输入各房间数字。",
      requiredIds: ["final_direction_code"],
      startsWhen: { type: "key_collected", id: "exit_key" },
      completesWhen: { type: "puzzle_completed", id: "final_direction_code" },
      nextObjectiveId: "reach_direction_code_exit",
      hudLabel: "方位密码",
    },
    {
      id: "reach_direction_code_exit",
      type: "reach_exit",
      title: "进入测试出口",
      detail: "最终门已打开。",
      requiredIds: ["final_direction_door"],
      startsWhen: { type: "puzzle_completed", id: "final_direction_code" },
      completesWhen: { type: "interaction_completed", id: "use_direction_code_exit" },
      hudLabel: "测试出口",
    },
  ],
  waves: [],
};

export const directionCodeSmokeValidationReport = validateLevelConfig(directionCodeSmokeLevel);
