import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const doorSwitchSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_door_switch_lab",
  title: "门开关 Smoke",
  spawnPoint: [0, 0, 5],
  initialWaveStartDelay: 0,
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  puzzles: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "switch_smoke_exit",
    position: [0, 0, -9.35],
    radius: 1.8,
    unlockMessage: "切换门组验证完成。",
    transitionMessage: "测试电梯确认门组状态切换。",
    victoryMessage: "Smoke 完成：开关、关门、锁门、开门全部由 config 驱动。",
  },
  map: {
    id: "smoke_door_switch_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "switch_spawn_room",
        label: "开关入口",
        bounds: { center: [0, 0, 4.8], size: [8, 4, 5.6] },
        mood: "quiet",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
        aesthetic: { style: "sterile", detail: "medium" },
      },
      {
        id: "switch_control_room",
        label: "门组控制间",
        bounds: { center: [0, 0, -1.2], size: [8, 4, 5.6] },
        mood: "uneasy",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ffd36d" },
        aesthetic: { style: "hazard", detail: "medium" },
      },
      {
        id: "switch_exit_room",
        label: "门组出口",
        bounds: { center: [0, 0, -7.3], size: [6.6, 4, 4.9] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
        aesthetic: { style: "exit", detail: "medium" },
      },
    ],
    doors: [
      {
        id: "switch_entry_door",
        label: "入口回路门",
        fromRoomId: "switch_spawn_room",
        toRoomId: "switch_control_room",
        position: [0, 0, 2],
        size: [3.4, 3.2, 0.35],
        yaw: 0,
        defaultState: "open",
        lock: { type: "none", unlockedMessage: "入口回路门已打开。" },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
        panelPosition: [1.9, 0, 2.35],
      },
      {
        id: "switch_exit_door",
        label: "出口回路门",
        fromRoomId: "switch_control_room",
        toRoomId: "switch_exit_room",
        position: [0, 0, -4.85],
        size: [3.4, 3.2, 0.35],
        yaw: 0,
        defaultState: "closed",
        lock: {
          type: "switch_state",
          switchId: "reroute_switch",
          stateId: "rerouted",
          manualOpen: false,
          lockedMessage: "门组未改道。",
          unlockedMessage: "出口回路门已打开。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.9, 0, -4.5],
      },
    ],
    keyItems: [],
    interactions: [
      {
        id: "reroute_switch_panel",
        type: "switch",
        roomId: "switch_control_room",
        position: [3.72, 1.34, -1.2],
        yaw: -Math.PI / 2,
        radius: 1.75,
        visualKey: "wall_door_switch_button",
        materialKey: "terminal_cyan",
        label: "门组墙面门控",
      },
      {
        id: "use_switch_smoke_exit",
        type: "exit",
        roomId: "switch_exit_room",
        position: [0, 0, -9.35],
        radius: 1.8,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入门组出口",
        requiresObjectiveId: "open_switch_exit_door",
      },
    ],
    navigation: {
      criticalPathRoomIds: ["switch_spawn_room", "switch_control_room", "switch_exit_room"],
      optionalRoomIds: [],
      maxBacktrackSeconds: 12,
      mobileReadableDoorCount: 2,
    },
  },
  switches: [
    {
      id: "reroute_switch",
      roomId: "switch_control_room",
      interactionId: "reroute_switch_panel",
      label: "门组墙面门控",
      initialStateId: "idle",
      oneShot: false,
      cycling: { mode: "next", wrap: true },
      wallMount: {
        roomId: "switch_control_room",
        side: "east",
        offset: 0,
        height: 1.34,
        inset: 0.28,
      },
      presentation: {
        kind: "wall_lever",
        modelKey: "hp_wall_door_switch_button_v1",
        handPose: "lever_push_down",
        hideWeapon: true,
        useDurationSec: 0.82,
        commitAtSec: 0.42,
        doorRevealSec: 2,
        revealMode: "door_front",
      },
      states: [
        {
          id: "idle",
          label: "入口开",
          detail: "入口开启，出口关闭",
          message: "门组回到入口通路。",
          rewardPulse: { label: "门组复位", detail: "前门开，后门关", rarity: "rare" },
          cameraImpact: { shake: 0.12, fovKick: 0.55 },
          actions: [
            { type: "unlock_door", doorId: "switch_entry_door" },
            { type: "open_door", doorId: "switch_entry_door" },
            { type: "close_door", doorId: "switch_exit_door" },
            { type: "lock_door", doorId: "switch_exit_door" },
          ],
        },
        {
          id: "rerouted",
          label: "改道",
          detail: "入口锁死，出口打开",
          message: "门组已改道。",
          rewardPulse: { label: "门组改道", detail: "前门关，后门开", rarity: "rare" },
          cameraImpact: { shake: 0.26, fovKick: 1.2 },
          audio: { key: "system_exit_open", intensity: 0.8 },
          actions: [
            { type: "close_door", doorId: "switch_entry_door" },
            { type: "lock_door", doorId: "switch_entry_door" },
            { type: "unlock_door", doorId: "switch_exit_door" },
            { type: "open_door", doorId: "switch_exit_door" },
            { type: "unlock_exit" },
          ],
        },
      ],
    },
  ],
  objectiveChain: [
    {
      id: "activate_reroute_switch",
      type: "custom",
      title: "切换门组",
      detail: "按下墙面门控，观察前后门状态。",
      requiredIds: ["reroute_switch:rerouted"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "switch_activated", id: "reroute_switch", optionId: "rerouted" },
      nextObjectiveId: "open_switch_exit_door",
      hudLabel: "门组开关",
      guidance: { targetType: "interaction", targetId: "reroute_switch_panel", label: "门组墙面门控", detail: "切换后前门锁死，出口打开。", urgency: "puzzle" },
    },
    {
      id: "open_switch_exit_door",
      type: "open_door",
      title: "穿过出口门",
      detail: "出口回路已打开。",
      requiredIds: ["switch_exit_door"],
      startsWhen: { type: "switch_activated", id: "reroute_switch", optionId: "rerouted" },
      completesWhen: { type: "door_opened", id: "switch_exit_door" },
      nextObjectiveId: "reach_switch_exit",
      hudLabel: "出口门",
      guidance: { targetType: "door", targetId: "switch_exit_door", label: "出口回路门", detail: "不要回头，直接离开。" },
    },
    {
      id: "reach_switch_exit",
      type: "reach_exit",
      title: "进入测试出口",
      detail: "验证门组状态可以通关。",
      requiredIds: ["use_switch_smoke_exit"],
      startsWhen: { type: "door_opened", id: "switch_exit_door" },
      completesWhen: { type: "interaction_completed", id: "use_switch_smoke_exit" },
      hudLabel: "测试出口",
    },
  ],
  waves: [],
};

export const doorSwitchSmokeValidationReport = validateLevelConfig(doorSwitchSmokeLevel);
