import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const keyDoorSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_key_door_lab",
  title: "钥匙门 Smoke",
  spawnPoint: [0, 0, 5.5],
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  puzzles: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "smoke_exit",
    position: [0, 0, -12],
    radius: 1.8,
    unlockMessage: "测试出口已解锁。",
  },
  map: {
    id: "smoke_key_door_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "spawn_lab",
        label: "出生实验间",
        bounds: { center: [0, 0, 4], size: [8, 4, 8] },
        mood: "quiet",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "locked_hall",
        label: "门禁走廊",
        bounds: { center: [0, 0, -4], size: [7, 4, 8] },
        mood: "uneasy",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ffb34f" },
      },
      {
        id: "exit_lift",
        label: "测试电梯",
        bounds: { center: [0, 0, -12], size: [6, 4, 5] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
    ],
    doors: [
      {
        id: "yellow_key_door",
        label: "黄色门禁门",
        fromRoomId: "spawn_lab",
        toRoomId: "locked_hall",
        position: [0, 0, 0],
        size: [3, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "key_item",
          keyItemId: "yellow_access_card",
          lockedMessage: "缺少黄色门禁片。",
          unlockedMessage: "黄色门禁已打开。",
        },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
        panelPosition: [1.75, 0, 0.35],
      },
      {
        id: "smoke_exit_door",
        label: "测试电梯门",
        fromRoomId: "locked_hall",
        toRoomId: "exit_lift",
        position: [0, 0, -8.75],
        size: [3.2, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "objective_complete",
          objectiveId: "inspect_exit_terminal",
          lockedMessage: "出口终端未确认。",
          unlockedMessage: "测试出口开启。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.85, 0, -8.4],
      },
    ],
    keyItems: [
      {
        id: "yellow_access_card",
        label: "黄色门禁片",
        roomId: "spawn_lab",
        position: [2.1, 0, 5.3],
        collectRadius: 1.45,
        visualKey: "yellow_access_card",
        materialKey: "access_card_gold",
        requiredForDoorIds: ["yellow_key_door"],
        rewardPulse: { label: "门禁片", detail: "黄色门可以打开", rarity: "rare" },
      },
    ],
    interactions: [
      {
        id: "inspect_exit_terminal",
        type: "terminal",
        roomId: "locked_hall",
        position: [2.2, 0, -5.8],
        radius: 1.55,
        visualKey: "sleep_record_terminal",
        materialKey: "terminal_cyan",
        label: "测试终端",
        rewardPulse: { label: "终端确认", detail: "出口门禁更新", rarity: "rare" },
      },
      {
        id: "use_smoke_exit",
        type: "exit",
        roomId: "exit_lift",
        position: [0, 0, -12],
        radius: 1.8,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入测试电梯",
        requiresObjectiveId: "inspect_exit_terminal",
      },
    ],
    navigation: {
      criticalPathRoomIds: ["spawn_lab", "locked_hall", "exit_lift"],
      optionalRoomIds: [],
      maxBacktrackSeconds: 10,
      mobileReadableDoorCount: 2,
    },
  },
  objectiveChain: [
    {
      id: "find_yellow_access_card",
      type: "collect_key",
      title: "找门禁片",
      detail: "拿到黄色门禁片，打开第一道门。",
      requiredIds: ["yellow_access_card"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "key_collected", id: "yellow_access_card" },
      nextObjectiveId: "open_yellow_key_door",
      hudLabel: "门禁片",
    },
    {
      id: "open_yellow_key_door",
      type: "open_door",
      title: "打开黄色门",
      detail: "靠近门禁面板，确认门锁。",
      requiredIds: ["yellow_key_door"],
      startsWhen: { type: "key_collected", id: "yellow_access_card" },
      completesWhen: { type: "door_opened", id: "yellow_key_door" },
      nextObjectiveId: "inspect_exit_terminal",
      hudLabel: "黄色门",
    },
    {
      id: "inspect_exit_terminal",
      type: "custom",
      title: "读取出口终端",
      detail: "终端会打开最后的电梯门。",
      requiredIds: ["inspect_exit_terminal"],
      startsWhen: { type: "door_opened", id: "yellow_key_door" },
      completesWhen: { type: "interaction_completed", id: "inspect_exit_terminal" },
      nextObjectiveId: "reach_smoke_exit",
      hudLabel: "终端",
    },
    {
      id: "reach_smoke_exit",
      type: "reach_exit",
      title: "进入测试电梯",
      detail: "验证钥匙门路径可以通关。",
      requiredIds: ["smoke_exit_door"],
      startsWhen: { type: "door_opened", id: "smoke_exit_door" },
      completesWhen: { type: "interaction_completed", id: "use_smoke_exit" },
      hudLabel: "测试出口",
    },
  ],
  waves: [
    {
      id: "smoke_hall_contact",
      startDelay: 0,
      trigger: { type: "door_opened", id: "yellow_key_door", delay: 0.25 },
      enemies: [{ archetype: "repair_drone", count: 1, from: "front" }],
      reward: "none",
    },
    {
      id: "smoke_terminal_alarm",
      startDelay: 0,
      trigger: { type: "interaction_completed", id: "inspect_exit_terminal", delay: 0.35 },
      enemies: [{ archetype: "clamp_bot", count: 1, from: "side_rear" }],
      reward: "open_exit",
    },
  ],
  presentation: {
    ...level01MaintenanceBay.presentation,
    waveLabels: {
      ...level01MaintenanceBay.presentation.waveLabels,
      smoke_hall_contact: "走廊接触",
      smoke_terminal_alarm: "终端警报",
    },
    waves: [
      ...level01MaintenanceBay.presentation.waves,
      {
        id: "smoke_hall_contact",
        label: "走廊接触",
        objectiveTitle: "门后有动静",
        objectiveDetail: "验证开门触发刷怪",
        startMessage: "门后的维修单位被唤醒。",
        startWarning: { label: "门后有动静", detail: "开门触发了维修单位" },
        startWarningDuration: 1.8,
        startAudio: { key: "elite_warning", intensity: 0.64 },
      },
      {
        id: "smoke_terminal_alarm",
        label: "终端警报",
        objectiveTitle: "终端暴露你",
        objectiveDetail: "验证互动触发刷怪",
        startMessage: "出口终端发出警报。",
        startWarning: { label: "终端警报", detail: "清掉它，出口才会开" },
        startWarningDuration: 1.9,
        startAudio: { key: "assist_reorient", intensity: 0.72 },
        startCamera: { shake: 0.28, fovKick: 1.8 },
      },
    ],
  },
};

export const keyDoorSmokeValidationReport = validateLevelConfig(keyDoorSmokeLevel);
