import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const keyOrbCodeSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_key_orb_code_lock",
  title: "钥匙 + 颜色球 + 方位密码 Smoke",
  spawnPoint: [0, 0, 8.8],
  initialWaveStartDelay: 0,
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "combo_escape_exit",
    position: [0, 0, -15.4],
    radius: 1.85,
    unlockMessage: "组合门禁全部通过。",
    unlockWarning: { label: "最终出口通电", detail: "钥匙、颜色球和方位密码全部确认" },
    transitionMessage: "Smoke 电梯下行：组合密室 config 路径可通关。",
    victoryMessage: "Smoke 完成：钥匙门、颜色球顺序和方位密码锁全部由 config 串联。",
  },
  pickups: {
    ...level01MaintenanceBay.pickups,
    storyPickups: [
      {
        type: "ironRod",
        interactionId: "combo_pickup_iron_rod",
        position: [-1.25, 0, 9.55],
        collectRadius: 1.65,
        grants: { hasRod: true, equipWeapon: "pulseRifle" },
        rewardPulse: { label: "拾起铁棒", detail: "用于击中颜色球", rarity: "rare" },
        rewardPulseDuration: 1.25,
        audio: { key: "ui_upgrade_select", intensity: 0.7 },
      },
      {
        type: "pistol",
        interactionId: "combo_pickup_pistol",
        position: [1.2, 0, 9.15],
        collectRadius: 1.65,
        grants: { hasPistol: true, equipWeapon: "pulseRifle" },
        rewardPulse: { label: "拾起手枪", detail: "远处也能打中颜色球", rarity: "rare" },
        rewardPulseDuration: 1.25,
        audio: { key: "ui_upgrade_select", intensity: 0.72 },
      },
    ],
  },
  map: {
    id: "smoke_key_orb_code_lock_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "combo_start_lab",
        label: "起点实验室",
        bounds: { center: [0, 0, 8], size: [8, 4, 6] },
        mood: "uneasy",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "combo_orb_chamber",
        label: "颜色球锁室",
        bounds: { center: [0, 0, 1.5], size: [8, 4, 6] },
        mood: "quiet",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#f7c65c" },
      },
      {
        id: "combo_code_hub",
        label: "方位密码大厅",
        bounds: { center: [0, 0, -4.8], size: [7, 4, 6] },
        mood: "uneasy",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "combo_north_digit_room",
        label: "北侧数字室",
        bounds: { center: [0, 0, -10.4], size: [5.5, 4, 4.5] },
        mood: "quiet",
        floorMaterialKey: "maintenance_bay_wet_floor",
        wallMaterialKey: "maintenance_bay_glass_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "combo_east_digit_room",
        label: "东侧数字室",
        bounds: { center: [6.2, 0, -4.8], size: [4.5, 4, 5] },
        mood: "quiet",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#f7c65c" },
      },
      {
        id: "combo_west_digit_room",
        label: "西侧数字室",
        bounds: { center: [-6.2, 0, -4.8], size: [4.5, 4, 5] },
        mood: "quiet",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
      {
        id: "combo_exit_room",
        label: "组合测试出口",
        bounds: { center: [0, 0, -15.4], size: [5.4, 4, 4.2] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
    ],
    doors: [
      {
        id: "combo_key_gate",
        label: "第一道钥匙门",
        fromRoomId: "combo_start_lab",
        toRoomId: "combo_orb_chamber",
        position: [0, 0, 4.75],
        size: [3.1, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "key_item",
          keyItemId: "combo_lab_key",
          lockedMessage: "需要起点实验室里的门禁钥匙。",
          unlockedMessage: "第一道门已打开。",
        },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
        panelPosition: [1.78, 0, 5.08],
        openSpeed: 1.25,
        cameraImpact: { shake: 0.14, fovKick: 0.8 },
      },
      {
        id: "combo_orb_gate",
        label: "颜色球联动门",
        fromRoomId: "combo_orb_chamber",
        toRoomId: "combo_code_hub",
        position: [0, 0, -1.65],
        size: [3.1, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "combo_color_orb_lock",
          lockedMessage: "颜色球顺序还没确认。",
          unlockedMessage: "颜色球联动门已打开。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.78, 0, -1.32],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.2, fovKick: 1.15 },
      },
      {
        id: "combo_north_digit_door",
        label: "北侧数字门",
        fromRoomId: "combo_code_hub",
        toRoomId: "combo_north_digit_room",
        position: [0, 0, -7.95],
        size: [2.7, 3, 0.32],
        yaw: 0,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
      },
      {
        id: "combo_east_digit_door",
        label: "东侧数字门",
        fromRoomId: "combo_code_hub",
        toRoomId: "combo_east_digit_room",
        position: [3.75, 0, -4.8],
        size: [2.7, 3, 0.32],
        yaw: Math.PI / 2,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
      },
      {
        id: "combo_west_digit_door",
        label: "西侧数字门",
        fromRoomId: "combo_code_hub",
        toRoomId: "combo_west_digit_room",
        position: [-3.75, 0, -4.8],
        size: [2.7, 3, 0.32],
        yaw: Math.PI / 2,
        defaultState: "open",
        lock: { type: "none" },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
      },
      {
        id: "combo_final_code_door",
        label: "最终方位门",
        fromRoomId: "combo_north_digit_room",
        toRoomId: "combo_exit_room",
        position: [0, 0, -13],
        size: [3.1, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "combo_final_direction_code",
          keyItemId: "combo_lab_key",
          lockedMessage: "需要钥匙和方位密码。",
          unlockedMessage: "最终方位门已打开。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.78, 0, -12.66],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.28, fovKick: 1.45 },
      },
    ],
    keyItems: [
      {
        id: "combo_lab_key",
        label: "组合门禁钥匙",
        roomId: "combo_start_lab",
        position: [-2.65, 0, 8.35],
        collectRadius: 1.45,
        visualKey: "yellow_access_card",
        materialKey: "access_card_gold",
        requiredForDoorIds: ["combo_key_gate", "combo_final_code_door"],
        rewardPulse: { label: "门禁钥匙", detail: "第一道门可打开", rarity: "rare" },
      },
    ],
    interactions: [
      {
        id: "combo_color_order_panel",
        type: "terminal",
        roomId: "combo_start_lab",
        position: [2.65, 0, 8.2],
        radius: 1.55,
        visualKey: "three_color_order_panel",
        materialKey: "terminal_cyan",
        label: "三色图案",
        rewardPulse: { label: "图案记录", detail: "黄 -> 红 -> 蓝", rarity: "rare" },
      },
      {
        id: "combo_direction_keypad",
        type: "door_panel",
        roomId: "combo_code_hub",
        position: [1.75, 0, -6.25],
        radius: 1.65,
        visualKey: "direction_keypad_panel",
        materialKey: "terminal_cyan",
        label: "方位密码面板",
      },
      {
        id: "use_combo_escape_exit",
        type: "exit",
        roomId: "combo_exit_room",
        position: [0, 0, -15.4],
        radius: 1.85,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入组合测试出口",
        requiresObjectiveId: "input_combo_final_code",
      },
    ],
    navigation: {
      criticalPathRoomIds: [
        "combo_start_lab",
        "combo_orb_chamber",
        "combo_code_hub",
        "combo_north_digit_room",
        "combo_exit_room",
      ],
      optionalRoomIds: ["combo_east_digit_room", "combo_west_digit_room"],
      maxBacktrackSeconds: 28,
      mobileReadableDoorCount: 5,
    },
  },
  puzzles: [
    {
      id: "combo_color_orb_lock",
      type: "hit_sequence",
      label: "组合颜色球锁",
      roomId: "combo_orb_chamber",
      clue: {
        type: "pattern_panel",
        roomId: "combo_start_lab",
        interactionId: "combo_color_order_panel",
        sequence: ["combo_yellow_orb", "combo_red_orb", "combo_blue_orb"],
        label: "黄 -> 红 -> 蓝",
      },
      input: {
        method: "weapon_hit",
        allowedWeapons: ["pulseRifle", "railLance"],
        resetOnMistake: true,
        showProgressPulse: true,
      },
      targets: [
        {
          id: "combo_yellow_orb",
          label: "黄色球",
          roomId: "combo_orb_chamber",
          position: [-2.35, 1.15, 1.3],
          radius: 0.72,
          colorKey: "yellow",
          visualKey: "puzzle_orb_yellow",
        },
        {
          id: "combo_red_orb",
          label: "红色球",
          roomId: "combo_orb_chamber",
          position: [0, 1.15, 0.1],
          radius: 0.72,
          colorKey: "red",
          visualKey: "puzzle_orb_red",
        },
        {
          id: "combo_blue_orb",
          label: "蓝色球",
          roomId: "combo_orb_chamber",
          position: [2.35, 1.15, 1.3],
          radius: 0.72,
          colorKey: "blue",
          visualKey: "puzzle_orb_blue",
        },
      ],
      fail: {
        message: "顺序错了，颜色球锁重置。",
        resetDelay: 0.45,
        cameraImpact: { shake: 0.16, fovKick: 0.65 },
        audio: { key: "enemy_hit", intensity: 0.42 },
      },
      success: {
        opensDoorId: "combo_orb_gate",
        completesObjectiveId: "solve_combo_color_orbs",
        rewardPulse: { label: "颜色联动解除", detail: "黄红蓝顺序确认", rarity: "epic" },
        rewardPulseDuration: 1.55,
        cameraImpact: { shake: 0.32, fovKick: 1.45, rumble: 0.2, rumbleDuration: 0.2 },
        audio: { key: "system_exit_open", intensity: 0.9 },
      },
    },
    {
      id: "combo_final_direction_code",
      type: "code_lock",
      label: "组合方位密码锁",
      roomId: "combo_code_hub",
      interactionId: "combo_direction_keypad",
      requiredKeyItemId: "combo_lab_key",
      code: {
        source: "direction_room_digits",
        directionOrder: ["south", "east", "west", "north"],
      },
      input: {
        length: 4,
        mode: "digit_buttons",
        allowBackspace: true,
        clearOnMistake: false,
        submitLabel: "确认最终门禁",
      },
      clues: [
        {
          id: "combo_south_digit",
          type: "number_decal",
          roomId: "combo_orb_chamber",
          direction: "south",
          value: "3",
          visualKey: "wall_digit_warning",
          position: [0, 1.55, 3.35],
          yaw: Math.PI,
          label: "南 3",
        },
        {
          id: "combo_east_digit",
          type: "number_decal",
          roomId: "combo_east_digit_room",
          direction: "east",
          value: "8",
          visualKey: "wall_digit_warning",
          position: [7.95, 1.55, -4.8],
          yaw: -Math.PI / 2,
          label: "东 8",
        },
        {
          id: "combo_west_digit",
          type: "number_decal",
          roomId: "combo_west_digit_room",
          direction: "west",
          value: "5",
          visualKey: "wall_digit_warning",
          position: [-7.95, 1.55, -4.8],
          yaw: Math.PI / 2,
          label: "西 5",
        },
        {
          id: "combo_north_digit",
          type: "number_decal",
          roomId: "combo_north_digit_room",
          direction: "north",
          value: "1",
          visualKey: "wall_digit_warning",
          position: [0, 1.55, -11.85],
          yaw: 0,
          label: "北 1",
        },
      ],
      fail: {
        message: "密码不对。组合门禁拒绝响应。",
        cameraImpact: { shake: 0.18, fovKick: 0.8 },
        audio: { key: "enemy_hit", intensity: 0.44 },
      },
      success: {
        opensDoorId: "combo_final_code_door",
        unlockExit: true,
        completesObjectiveId: "input_combo_final_code",
        rewardPulse: { label: "最终门禁解除", detail: "南-东-西-北密码确认", rarity: "epic" },
        rewardPulseDuration: 1.65,
        cameraImpact: { shake: 0.36, fovKick: 1.65, rumble: 0.24, rumbleDuration: 0.24 },
        audio: { key: "system_exit_open", intensity: 1 },
      },
    },
  ],
  objectiveChain: [
    {
      id: "find_combo_lab_key",
      type: "collect_key",
      title: "找门禁钥匙",
      detail: "先拿起起点实验室里的钥匙。",
      requiredIds: ["combo_lab_key"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "key_collected", id: "combo_lab_key" },
      nextObjectiveId: "inspect_combo_color_order",
      hudLabel: "门禁钥匙",
    },
    {
      id: "inspect_combo_color_order",
      type: "inspect_all",
      title: "读取三色图案",
      detail: "图案决定颜色球攻击顺序。",
      requiredIds: ["combo_color_order_panel"],
      startsWhen: { type: "key_collected", id: "combo_lab_key" },
      completesWhen: { type: "interaction_completed", id: "combo_color_order_panel" },
      nextObjectiveId: "open_combo_key_gate",
      hudLabel: "三色图案",
    },
    {
      id: "open_combo_key_gate",
      type: "open_door",
      title: "打开钥匙门",
      detail: "进入颜色球锁室。",
      requiredIds: ["combo_key_gate"],
      startsWhen: { type: "interaction_completed", id: "combo_color_order_panel" },
      completesWhen: { type: "door_opened", id: "combo_key_gate" },
      nextObjectiveId: "solve_combo_color_orbs",
      hudLabel: "钥匙门",
    },
    {
      id: "solve_combo_color_orbs",
      type: "custom",
      title: "击中颜色球",
      detail: "按图案顺序攻击颜色球。",
      requiredIds: ["combo_color_orb_lock"],
      startsWhen: { type: "door_opened", id: "combo_key_gate" },
      completesWhen: { type: "puzzle_completed", id: "combo_color_orb_lock" },
      nextObjectiveId: "input_combo_final_code",
      hudLabel: "颜色顺序",
    },
    {
      id: "input_combo_final_code",
      type: "custom",
      title: "输入方位密码",
      detail: "按面板上的方位顺序输入房间数字。",
      requiredIds: ["combo_final_direction_code"],
      startsWhen: { type: "puzzle_completed", id: "combo_color_orb_lock" },
      completesWhen: { type: "puzzle_completed", id: "combo_final_direction_code" },
      nextObjectiveId: "reach_combo_escape_exit",
      hudLabel: "方位密码",
    },
    {
      id: "reach_combo_escape_exit",
      type: "reach_exit",
      title: "进入组合出口",
      detail: "完整组合密室路径已通过。",
      requiredIds: ["combo_final_code_door"],
      startsWhen: { type: "puzzle_completed", id: "combo_final_direction_code" },
      completesWhen: { type: "interaction_completed", id: "use_combo_escape_exit" },
      hudLabel: "组合出口",
    },
  ],
  waves: [],
};

export const keyOrbCodeSmokeValidationReport = validateLevelConfig(keyOrbCodeSmokeLevel);
