import { validateLevelConfig } from "../ConfigValidator";
import { level01MaintenanceBay } from "../levelManifest";
import type { LevelDefinition } from "../schema/levelConfig";

export const puzzleOrbSmokeLevel: LevelDefinition = {
  ...level01MaintenanceBay,
  id: "smoke_color_orb_lock",
  title: "颜色球门锁 Smoke",
  spawnPoint: [0, 0, 6.8],
  initialWaveStartDelay: 0,
  requiresStoryPickupsBeforeWaves: false,
  events: [],
  environmentStates: [],
  exit: {
    ...level01MaintenanceBay.exit,
    id: "puzzle_smoke_exit",
    position: [0, 0, -9.3],
    radius: 1.8,
    unlockMessage: "出口门禁收到颜色顺序确认。",
    unlockWarning: { label: "出口已通电", detail: "颜色顺序正确，后门打开" },
    transitionMessage: "测试电梯下行，门后还有更复杂的房间。",
    victoryMessage: "Smoke 完成：钥匙、顺序球、门锁、出口全部由 config 驱动。",
  },
  map: {
    id: "smoke_color_orb_lock_map",
    schemaVersion: "hp.map.v1",
    rooms: [
      {
        id: "puzzle_main_hall",
        label: "图案大厅",
        bounds: { center: [0, 0, 5.2], size: [9, 4, 7.6] },
        mood: "uneasy",
        floorMaterialKey: "sterile_lab_floor",
        wallMaterialKey: "sterile_lab_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#64d7ff" },
      },
      {
        id: "orb_chamber",
        label: "颜色球锁室",
        bounds: { center: [0, 0, -2.6], size: [9, 4, 7.6] },
        mood: "quiet",
        floorMaterialKey: "hazard_hall_floor",
        wallMaterialKey: "hazard_hall_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#f7c65c" },
      },
      {
        id: "puzzle_exit_room",
        label: "测试出口",
        bounds: { center: [0, 0, -8.6], size: [6.5, 4, 4.4] },
        mood: "reveal",
        floorMaterialKey: "red_exit_floor",
        wallMaterialKey: "red_exit_wall",
        geometry: { renderFloor: true, renderWalls: true, collisionWalls: true, accentColor: "#ff5b4c" },
      },
    ],
    doors: [
      {
        id: "orb_key_door",
        label: "球锁室门禁",
        fromRoomId: "puzzle_main_hall",
        toRoomId: "orb_chamber",
        position: [0, 0, 1.3],
        size: [3.2, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "key_item",
          keyItemId: "blue_lab_key",
          lockedMessage: "门禁片缺失。大厅里应该有备用片。",
          unlockedMessage: "球锁室门禁已打开。",
        },
        visualKey: "yellow_access_door",
        materialKey: "yellow_access_metal",
        panelPosition: [1.78, 0, 1.62],
        openSpeed: 1.25,
        cameraImpact: { shake: 0.14, fovKick: 0.8 },
      },
      {
        id: "orb_reward_door",
        label: "后门颜色锁",
        fromRoomId: "orb_chamber",
        toRoomId: "puzzle_exit_room",
        position: [0, 0, -6.35],
        size: [3.1, 3.2, 0.35],
        yaw: 0,
        defaultState: "locked",
        lock: {
          type: "puzzle_complete",
          puzzleId: "hall_color_orb_lock",
          lockedMessage: "颜色顺序未确认。",
          unlockedMessage: "颜色锁解除。",
        },
        visualKey: "service_elevator_door",
        materialKey: "service_elevator_metal",
        panelPosition: [1.78, 0, -6.02],
        openSpeed: 1.35,
        cameraImpact: { shake: 0.2, fovKick: 1.2 },
      },
    ],
    keyItems: [
      {
        id: "blue_lab_key",
        label: "蓝色门禁片",
        roomId: "puzzle_main_hall",
        position: [-2.6, 0, 6.4],
        collectRadius: 1.45,
        visualKey: "yellow_access_card",
        materialKey: "terminal_cyan",
        requiredForDoorIds: ["orb_key_door"],
        rewardPulse: { label: "门禁片", detail: "球锁室可以打开", rarity: "rare" },
      },
    ],
    interactions: [
      {
        id: "inspect_color_order_panel",
        type: "terminal",
        roomId: "puzzle_main_hall",
        position: [2.6, 0, 5.25],
        radius: 1.55,
        visualKey: "three_color_order_panel",
        materialKey: "terminal_cyan",
        label: "三色图案",
        rewardPulse: { label: "图案记录", detail: "红 -> 蓝 -> 绿", rarity: "rare" },
      },
      {
        id: "use_puzzle_smoke_exit",
        type: "exit",
        roomId: "puzzle_exit_room",
        position: [0, 0, -9.3],
        radius: 1.8,
        visualKey: "exit_panel",
        materialKey: "terminal_red",
        label: "进入测试出口",
        requiresObjectiveId: "solve_hall_color_orbs",
      },
    ],
    navigation: {
      criticalPathRoomIds: ["puzzle_main_hall", "orb_chamber", "puzzle_exit_room"],
      optionalRoomIds: [],
      maxBacktrackSeconds: 16,
      mobileReadableDoorCount: 2,
    },
  },
  puzzles: [
    {
      id: "hall_color_orb_lock",
      type: "hit_sequence",
      label: "颜色球门锁",
      roomId: "orb_chamber",
      clue: {
        type: "pattern_panel",
        roomId: "puzzle_main_hall",
        interactionId: "inspect_color_order_panel",
        sequence: ["red_orb", "blue_orb", "green_orb"],
        label: "红 -> 蓝 -> 绿",
      },
      input: {
        method: "weapon_hit",
        allowedWeapons: ["pulseRifle", "railLance"],
        resetOnMistake: true,
        showProgressPulse: true,
      },
      targets: [
        {
          id: "red_orb",
          label: "红色球",
          roomId: "orb_chamber",
          position: [-2.45, 1.15, -3.45],
          radius: 0.72,
          colorKey: "red",
          visualKey: "puzzle_orb_red",
        },
        {
          id: "blue_orb",
          label: "蓝色球",
          roomId: "orb_chamber",
          position: [0, 1.15, -4.85],
          radius: 0.72,
          colorKey: "blue",
          visualKey: "puzzle_orb_blue",
        },
        {
          id: "green_orb",
          label: "绿色球",
          roomId: "orb_chamber",
          position: [2.45, 1.15, -3.45],
          radius: 0.72,
          colorKey: "green",
          visualKey: "puzzle_orb_green",
        },
      ],
      fail: {
        message: "顺序错了，颜色锁重置。",
        resetDelay: 0.45,
        cameraImpact: { shake: 0.16, fovKick: 0.65 },
        audio: { key: "enemy_hit", intensity: 0.42 },
      },
      success: {
        opensDoorId: "orb_reward_door",
        unlockExit: true,
        completesObjectiveId: "solve_hall_color_orbs",
        rewardPulse: { label: "颜色锁解除", detail: "红蓝绿顺序确认", rarity: "epic" },
        rewardPulseDuration: 1.6,
        cameraImpact: { shake: 0.34, fovKick: 1.6, rumble: 0.25, rumbleDuration: 0.24 },
        audio: { key: "system_exit_open", intensity: 0.95 },
      },
    },
  ],
  objectiveChain: [
    {
      id: "find_blue_lab_key",
      type: "collect_key",
      title: "找门禁片",
      detail: "大厅里有备用门禁片。",
      requiredIds: ["blue_lab_key"],
      startsWhen: { type: "level_start" },
      completesWhen: { type: "key_collected", id: "blue_lab_key" },
      nextObjectiveId: "open_orb_key_door",
      hudLabel: "门禁片",
    },
    {
      id: "open_orb_key_door",
      type: "open_door",
      title: "打开球锁室",
      detail: "门后的颜色球需要按顺序击中。",
      requiredIds: ["orb_key_door"],
      startsWhen: { type: "key_collected", id: "blue_lab_key" },
      completesWhen: { type: "door_opened", id: "orb_key_door" },
      nextObjectiveId: "inspect_color_order",
      hudLabel: "球锁室",
    },
    {
      id: "inspect_color_order",
      type: "inspect_all",
      title: "记住大厅图案",
      detail: "图案给出颜色球顺序。",
      requiredIds: ["inspect_color_order_panel"],
      startsWhen: { type: "door_opened", id: "orb_key_door" },
      completesWhen: { type: "interaction_completed", id: "inspect_color_order_panel" },
      nextObjectiveId: "solve_hall_color_orbs",
      hudLabel: "颜色图案",
    },
    {
      id: "solve_hall_color_orbs",
      type: "custom",
      title: "击中颜色球",
      detail: "按大厅图案顺序攻击颜色球。",
      requiredIds: ["hall_color_orb_lock"],
      startsWhen: { type: "interaction_completed", id: "inspect_color_order_panel" },
      completesWhen: { type: "puzzle_completed", id: "hall_color_orb_lock" },
      nextObjectiveId: "reach_puzzle_smoke_exit",
      hudLabel: "颜色顺序",
    },
    {
      id: "reach_puzzle_smoke_exit",
      type: "reach_exit",
      title: "进入测试出口",
      detail: "验证谜题门锁路径可以通关。",
      requiredIds: ["orb_reward_door"],
      startsWhen: { type: "puzzle_completed", id: "hall_color_orb_lock" },
      completesWhen: { type: "interaction_completed", id: "use_puzzle_smoke_exit" },
      hudLabel: "测试出口",
    },
  ],
  waves: [],
  presentation: {
    ...level01MaintenanceBay.presentation,
    waveLabels: {
      ...level01MaintenanceBay.presentation.waveLabels,
    },
  },
};

export const puzzleOrbSmokeValidationReport = validateLevelConfig(puzzleOrbSmokeLevel);
