import type { LevelMapConfig } from "../../schema/levelConfig";

export const level04Map: LevelMapConfig = {
  id: "level_04_memory_clinic_map",
  schemaVersion: "hp.map.v1",
  presentation: {
    archetype: "story_lab",
    shellKit: "hp:memory_clinic_shell_v1",
    lightingPreset: "hp:memory_clinic_sterile_v1",
    overrides: {
      propDensity: "sparse",
      floorWear: 0.18,
      ceilingLightIntensity: 1.05,
      doorStateStyle: "clinic_cyan_to_red",
      fogFar: 86,
    },
  },
  rooms: [
    {
      id: "level_04_entry_decon",
      label: "入口消毒间",
      bounds: { center: [0, 0, 18], size: [8, 4, 5] },
      mood: "quiet",
      skinKey: "memory_clinic_sterile",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.32,
      entryDialogueTrigger: "level_start",
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#9ff3ff" },
      aesthetic: { style: "sterile", detail: "medium", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_waiting_room",
      label: "候诊厅",
      bounds: { center: [0, 0, 10.5], size: [16, 4, 10] },
      mood: "uneasy",
      skinKey: "memory_clinic_sterile",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.54,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#7ff2ff" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_childhood_chair",
      label: "童年椅室",
      bounds: { center: [-11.5, 0, 10.5], size: [7, 4, 7] },
      mood: "quiet",
      skinKey: "memory_clinic_sterile",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.58,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ffd58a" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_rescue_chair",
      label: "救援椅室",
      bounds: { center: [11.5, 0, 10.5], size: [7, 4, 7] },
      mood: "uneasy",
      skinKey: "memory_clinic_sterile",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.62,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#8aeefc" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_body_chair",
      label: "身体椅室",
      bounds: { center: [0, 0, 1], size: [10, 4, 9] },
      mood: "reveal",
      skinKey: "sterile_blue_lab",
      floorMaterialKey: "memory_clinic_floor",
      wallMaterialKey: "memory_clinic_wall",
      ambientPressure: 0.76,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ff6a52" },
      aesthetic: { style: "sterile", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_therapy_theater",
      label: "治疗剧场",
      bounds: { center: [0, 0, -8], size: [14, 4, 9] },
      mood: "boss",
      skinKey: "reclamation_core_chamber",
      floorMaterialKey: "reclamation_core_floor",
      wallMaterialKey: "reclamation_core_wall",
      ambientPressure: 0.9,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#ff5b4c" },
      aesthetic: { style: "hazard", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
    {
      id: "level_04_exit_room",
      label: "出院电梯间",
      bounds: { center: [0, 0, -15.5], size: [7, 4, 6] },
      mood: "reveal",
      skinKey: "service_exit_red",
      floorMaterialKey: "red_exit_floor",
      wallMaterialKey: "red_exit_wall",
      ambientPressure: 0.68,
      geometry: { renderFloor: true, renderWalls: true, renderCeiling: true, collisionWalls: true, accentColor: "#fff3df" },
      aesthetic: { style: "exit", detail: "high", trim: true, wallPanels: true, ceilingLights: true, floorLines: true },
    },
  ],
  doors: [
    {
      id: "level_04_waiting_door",
      label: "诊所候诊门",
      fromRoomId: "level_04_entry_decon",
      toRoomId: "level_04_waiting_room",
      position: [0, 0, 15.5],
      size: [3.2, 2.8, 0.36],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "候诊厅门打开。" },
      visualKey: "clinic_memory_door",
      materialKey: "memory_clinic_wall",
      openSpeed: 1.15,
      cameraImpact: { shake: 0.12, fovKick: 0.65 },
    },
    {
      id: "level_04_childhood_door",
      label: "童年椅室门",
      fromRoomId: "level_04_waiting_room",
      toRoomId: "level_04_childhood_chair",
      position: [-8, 0, 10.5],
      size: [2.35, 2.65, 0.32],
      yaw: Math.PI / 2,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "童年椅室门打开。" },
      visualKey: "clinic_memory_door",
      materialKey: "memory_clinic_wall",
      panelPosition: [-7.6, 0, 12.2],
      openSpeed: 1.08,
    },
    {
      id: "level_04_rescue_door",
      label: "救援椅室门",
      fromRoomId: "level_04_waiting_room",
      toRoomId: "level_04_rescue_chair",
      position: [8, 0, 10.5],
      size: [2.35, 2.65, 0.32],
      yaw: Math.PI / 2,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "救援椅室门打开。" },
      visualKey: "clinic_memory_door",
      materialKey: "memory_clinic_wall",
      panelPosition: [7.6, 0, 8.9],
      openSpeed: 1.08,
    },
    {
      id: "level_04_body_door",
      label: "身体椅室门",
      fromRoomId: "level_04_waiting_room",
      toRoomId: "level_04_body_chair",
      position: [0, 0, 5.5],
      size: [3.1, 2.8, 0.36],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "身体椅室门打开。" },
      visualKey: "clinic_memory_door",
      materialKey: "memory_clinic_wall",
      panelPosition: [2.2, 0, 5.86],
      openSpeed: 1.12,
    },
    {
      id: "level_04_theater_door",
      label: "治疗剧场门",
      fromRoomId: "level_04_body_chair",
      toRoomId: "level_04_therapy_theater",
      position: [0, 0, -3.5],
      size: [4.2, 3.1, 0.42],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "治疗剧场门打开。" },
      visualKey: "industrial_access_door",
      materialKey: "terminal_red",
      panelPosition: [2.7, 0, -3.12],
      openSpeed: 1.22,
      cameraImpact: { shake: 0.22, fovKick: 1.2 },
    },
    {
      id: "level_04_exit_door",
      label: "出院电梯门",
      fromRoomId: "level_04_therapy_theater",
      toRoomId: "level_04_exit_room",
      position: [0, 0, -12.5],
      size: [4.4, 3.25, 0.44],
      yaw: 0,
      defaultState: "closed",
      lock: { type: "none", unlockedMessage: "出院电梯门打开。" },
      visualKey: "service_elevator_door",
      materialKey: "service_elevator_metal",
      panelPosition: [2.82, 0, -12.12],
      openSpeed: 1.26,
      cameraImpact: { shake: 0.34, fovKick: 1.85, rumble: 0.14, rumbleDuration: 0.2 },
    },
  ],
  keyItems: [],
  interactions: [
    {
      id: "level_04_exit_interaction",
      type: "exit",
      roomId: "level_04_exit_room",
      position: [0, 0, -16.6],
      radius: 2.35,
      visualKey: "service_elevator_panel",
      materialKey: "terminal_cyan",
      label: "进入出院电梯",
      opensDoorId: "level_04_exit_door",
    },
  ],
  pickups: [],
  props: [],
  navigation: {
    criticalPathRoomIds: [
      "level_04_entry_decon",
      "level_04_waiting_room",
      "level_04_body_chair",
      "level_04_therapy_theater",
      "level_04_exit_room",
    ],
    optionalRoomIds: ["level_04_childhood_chair", "level_04_rescue_chair"],
    maxBacktrackSeconds: 34,
    mobileReadableDoorCount: 6,
  },
};
