import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { MeshoptDecoder } from "three/examples/jsm/libs/meshopt_decoder.module.js";
import type { Object3D } from "three";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";
import type { LevelDoorDefinition, LevelInteractionDefinition, LevelPuzzleTargetDefinition } from "../game/config/schema/levelConfig";
import type { PickupType } from "../game/entities/EntityTypes";
import { doorVisualIntentForDefinition } from "../game/visual/intents/DoorVisualIntent";
import { interactionVisualModelKey } from "../game/visual/intents/InteractionVisualIntent";
import { puzzleTargetVisualModelKey } from "../game/visual/intents/PuzzleTargetVisualIntent";
import { pickupVisualIntentForType } from "../game/visual/PickupVisualIntent";
import { builderPuzzleMachineEnvironmentModelAssets } from "./registry/environment/builderPuzzleMachines";
import { generatedBuilderPackEnvironmentModelAssets } from "./registry/environment/generatedBuilderAssetPacks";
import { doorEnvironmentModelAssets } from "./registry/environment/doors";
import { level01EnvironmentModelAssets } from "./registry/environment/level01";
import { level02EnvironmentModelAssets } from "./registry/environment/level02";
import { level03EnvironmentModelAssets } from "./registry/environment/level03";
import { level04EnvironmentModelAssets } from "./registry/environment/level04";
import { pickupEnvironmentModelAssets } from "./registry/environment/pickups";
import { roomPropEnvironmentModelAssets } from "./registry/environment/props";
import { shellEnvironmentModelAssets } from "./registry/environment/shells";
import { terminalEnvironmentModelAssets } from "./registry/environment/terminals";
import type { EnvironmentModelAsset } from "./registry/environment/types";

export type EnvironmentModelKey = keyof typeof environmentModelAssets;
export type { EnvironmentModelAsset };

export const environmentModelAssets = {
  ...doorEnvironmentModelAssets,
  ...level01EnvironmentModelAssets,
  ...level02EnvironmentModelAssets,
  ...level03EnvironmentModelAssets,
  ...level04EnvironmentModelAssets,
  ...shellEnvironmentModelAssets,
  ...pickupEnvironmentModelAssets,
  ...roomPropEnvironmentModelAssets,
  ...terminalEnvironmentModelAssets,
  ...builderPuzzleMachineEnvironmentModelAssets,
  // Ingested external asset packs (regenerated by generate-builder-asset-pack-registry.mjs --emit).
  ...generatedBuilderPackEnvironmentModelAssets,
} as const satisfies Record<string, EnvironmentModelAsset>;

const loader = new GLTFLoader();
loader.setMeshoptDecoder(MeshoptDecoder);
const loadedScenes = new Map<EnvironmentModelKey, Object3D>();
const loadingPromises = new Map<EnvironmentModelKey, Promise<Object3D>>();
let preloadPromise: Promise<void> | null = null;

export function requiredEnvironmentModelCount() {
  return Object.keys(environmentModelAssets).length;
}

export function getEnvironmentModelAsset(modelKey: EnvironmentModelKey) {
  return environmentModelAssets[modelKey];
}

export function isEnvironmentModelKey(modelKey: string): modelKey is EnvironmentModelKey {
  return Object.prototype.hasOwnProperty.call(environmentModelAssets, modelKey);
}

export function getLoadedEnvironmentModel(modelKey: EnvironmentModelKey) {
  const model = loadedScenes.get(modelKey);
  if (!model) {
    throw new Error(`Required environment model "${modelKey}" has not finished loading.`);
  }
  return model;
}

export function getLoadedEnvironmentModelIfReady(modelKey: EnvironmentModelKey) {
  return loadedScenes.get(modelKey) ?? null;
}

export function loadEnvironmentModelAsset(modelKey: EnvironmentModelKey) {
  const loaded = loadedScenes.get(modelKey);
  if (loaded) return Promise.resolve(loaded);

  const pending = loadingPromises.get(modelKey);
  if (pending) return pending;

  const asset = environmentModelAssets[modelKey];
  const promise = loadGltf(asset.url)
    .then((gltf) => {
      loadedScenes.set(modelKey, gltf.scene);
      return gltf.scene;
    })
    .catch((error: unknown) => {
      loadingPromises.delete(modelKey);
      throw error;
    });
  loadingPromises.set(modelKey, promise);
  return promise;
}

export function preloadEnvironmentModelAssets(onProgress?: (loaded: number, total: number) => void) {
  if (preloadPromise) return preloadPromise;

  const entries = Object.entries(environmentModelAssets) as [EnvironmentModelKey, EnvironmentModelAsset][];
  let loaded = 0;
  const tick = () => {
    loaded += 1;
    onProgress?.(loaded, entries.length);
  };

  preloadPromise = preloadEnvironmentModelQueue(entries.map(([modelKey]) => modelKey), tick);

  return preloadPromise;
}

async function preloadEnvironmentModelQueue(modelKeys: readonly EnvironmentModelKey[], onLoaded: () => void) {
  const concurrency = 3;
  let nextIndex = 0;

  async function worker() {
    while (nextIndex < modelKeys.length) {
      const modelKey = modelKeys[nextIndex];
      nextIndex += 1;
      await loadEnvironmentModelAsset(modelKey);
      onLoaded();
      await yieldToBrowserFrame();
    }
  }

  await Promise.all(Array.from({ length: Math.min(concurrency, modelKeys.length) }, () => worker()));
}

export function modelKeyForDoor(door: LevelDoorDefinition): EnvironmentModelKey {
  return doorVisualIntentForDefinition(door).modelKey;
}

export function modelKeyForKeyVisual(visualKey: string): EnvironmentModelKey {
  if (visualKey === "large_yellow_key") return "pickup_large_yellow_key";
  if (visualKey === "route_output_orb_1") return "pickup_route_output_orb_1";
  if (visualKey === "route_output_orb_2") return "pickup_route_output_orb_2";
  if (visualKey === "route_output_orb_3") return "pickup_route_output_orb_3";
  if (visualKey === "route_output_orb_4") return "pickup_route_output_orb_4";
  if (visualKey === "family_access_card" || visualKey === "yellow_access_card" || visualKey === "route_access_chip") return "pickup_memory_chip_cluster";
  return "pickup_large_yellow_key";
}

export function modelKeyForPickupType(type: PickupType): EnvironmentModelKey | null {
  return pickupVisualIntentForType(type)?.modelKey ?? null;
}

export function modelKeyForPuzzleOrbTarget(target: LevelPuzzleTargetDefinition): string | null {
  return puzzleTargetVisualModelKey(target);
}

export function modelKeyForInteraction(interaction: LevelInteractionDefinition): EnvironmentModelKey | null {
  const modelKey = interactionVisualModelKey(interaction);
  return modelKey && isEnvironmentModelKey(modelKey) ? modelKey : null;
}

function loadGltf(url: string) {
  return new Promise<GLTF>((resolve, reject) => {
    loader.load(url, resolve, undefined, reject);
  });
}

function yieldToBrowserFrame() {
  if (typeof window === "undefined" || typeof window.requestAnimationFrame !== "function") {
    return Promise.resolve();
  }
  return new Promise<void>((resolve) => {
    window.requestAnimationFrame(() => resolve());
  });
}
